// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,"clk", false,-1);
    tracep->declBit(c+2,"rst", false,-1);
    tracep->declBit(c+3,"trigger", false,-1);
    tracep->declBus(c+4,"a0", false,-1, 31,0);
    tracep->declBus(c+5,"a1", false,-1, 31,0);
    tracep->declBus(c+6,"a2", false,-1, 31,0);
    tracep->declBus(c+7,"a3", false,-1, 31,0);
    tracep->declBus(c+8,"a4", false,-1, 31,0);
    tracep->declBus(c+9,"a5", false,-1, 31,0);
    tracep->declBus(c+10,"a6", false,-1, 31,0);
    tracep->declBus(c+11,"a7", false,-1, 31,0);
    tracep->declBus(c+12,"t0", false,-1, 31,0);
    tracep->declBus(c+13,"t1", false,-1, 31,0);
    tracep->declBus(c+14,"t2", false,-1, 31,0);
    tracep->declBus(c+15,"t3", false,-1, 31,0);
    tracep->declBus(c+16,"t4", false,-1, 31,0);
    tracep->declBus(c+17,"t5", false,-1, 31,0);
    tracep->declBus(c+18,"t6", false,-1, 31,0);
    tracep->declBus(c+19,"s0", false,-1, 31,0);
    tracep->declBus(c+20,"s1", false,-1, 31,0);
    tracep->declBus(c+21,"s2", false,-1, 31,0);
    tracep->declBus(c+22,"s3", false,-1, 31,0);
    tracep->declBus(c+23,"s4", false,-1, 31,0);
    tracep->declBus(c+24,"s5", false,-1, 31,0);
    tracep->declBus(c+25,"s6", false,-1, 31,0);
    tracep->declBus(c+26,"s7", false,-1, 31,0);
    tracep->declBus(c+27,"s8", false,-1, 31,0);
    tracep->declBus(c+28,"s9", false,-1, 31,0);
    tracep->declBus(c+29,"s10", false,-1, 31,0);
    tracep->declBus(c+30,"s11", false,-1, 31,0);
    tracep->pushNamePrefix("top ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+31,"clk", false,-1);
    tracep->declBit(c+32,"rst", false,-1);
    tracep->declBit(c+33,"trigger", false,-1);
    tracep->declBus(c+34,"a0", false,-1, 31,0);
    tracep->declBus(c+35,"a1", false,-1, 31,0);
    tracep->declBus(c+36,"a2", false,-1, 31,0);
    tracep->declBus(c+37,"a3", false,-1, 31,0);
    tracep->declBus(c+38,"a4", false,-1, 31,0);
    tracep->declBus(c+39,"a5", false,-1, 31,0);
    tracep->declBus(c+40,"a6", false,-1, 31,0);
    tracep->declBus(c+41,"a7", false,-1, 31,0);
    tracep->declBus(c+42,"t0", false,-1, 31,0);
    tracep->declBus(c+43,"t1", false,-1, 31,0);
    tracep->declBus(c+44,"t2", false,-1, 31,0);
    tracep->declBus(c+45,"t3", false,-1, 31,0);
    tracep->declBus(c+46,"t4", false,-1, 31,0);
    tracep->declBus(c+47,"t5", false,-1, 31,0);
    tracep->declBus(c+48,"t6", false,-1, 31,0);
    tracep->declBus(c+49,"s0", false,-1, 31,0);
    tracep->declBus(c+50,"s1", false,-1, 31,0);
    tracep->declBus(c+51,"s2", false,-1, 31,0);
    tracep->declBus(c+52,"s3", false,-1, 31,0);
    tracep->declBus(c+53,"s4", false,-1, 31,0);
    tracep->declBus(c+54,"s5", false,-1, 31,0);
    tracep->declBus(c+55,"s6", false,-1, 31,0);
    tracep->declBus(c+56,"s7", false,-1, 31,0);
    tracep->declBus(c+57,"s8", false,-1, 31,0);
    tracep->declBus(c+58,"s9", false,-1, 31,0);
    tracep->declBus(c+59,"s10", false,-1, 31,0);
    tracep->declBus(c+60,"s11", false,-1, 31,0);
    tracep->declBus(c+61,"PCF", false,-1, 31,0);
    tracep->declBus(c+62,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+63,"PC", false,-1, 31,0);
    tracep->declBus(c+64,"InstrF", false,-1, 31,0);
    tracep->declBus(c+65,"PCD", false,-1, 31,0);
    tracep->declBus(c+66,"PCPlus4D", false,-1, 31,0);
    tracep->declBus(c+67,"InstrD", false,-1, 31,0);
    tracep->declBus(c+68,"RD1E", false,-1, 31,0);
    tracep->declBus(c+69,"RD2E", false,-1, 31,0);
    tracep->declBus(c+70,"PCE", false,-1, 31,0);
    tracep->declBus(c+71,"PCPlus4E", false,-1, 31,0);
    tracep->declBus(c+72,"RdE", false,-1, 4,0);
    tracep->declBit(c+73,"RegWriteE", false,-1);
    tracep->declBit(c+74,"ALUSrcE", false,-1);
    tracep->declBit(c+75,"MemWriteE", false,-1);
    tracep->declBus(c+76,"ResultSrcE", false,-1, 1,0);
    tracep->declBus(c+77,"ALUControlE", false,-1, 3,0);
    tracep->declBus(c+78,"modeBUE", false,-1, 2,0);
    tracep->declBus(c+79,"WriteDataE", false,-1, 31,0);
    tracep->declBus(c+80,"ALUResultM", false,-1, 31,0);
    tracep->declBus(c+81,"WriteDataM", false,-1, 31,0);
    tracep->declBus(c+82,"RdM", false,-1, 4,0);
    tracep->declBit(c+83,"RegWriteM", false,-1);
    tracep->declBit(c+84,"MemWriteM", false,-1);
    tracep->declBus(c+85,"ResultSrcM", false,-1, 1,0);
    tracep->declBus(c+86,"modeBUM", false,-1, 2,0);
    tracep->declBus(c+87,"PCPlus4M", false,-1, 31,0);
    tracep->declBus(c+88,"ALUResultW", false,-1, 31,0);
    tracep->declBus(c+89,"ReadDataW", false,-1, 31,0);
    tracep->declBus(c+90,"RdW", false,-1, 4,0);
    tracep->declBit(c+91,"RegWriteW", false,-1);
    tracep->declBus(c+92,"ResultSrcW", false,-1, 1,0);
    tracep->declBus(c+93,"PCPlus4W", false,-1, 31,0);
    tracep->declBus(c+94,"ExtImmD", false,-1, 31,0);
    tracep->declBus(c+95,"ExtImmE", false,-1, 31,0);
    tracep->declBus(c+96,"ImmSrcD", false,-1, 2,0);
    tracep->declBit(c+97,"RegWriteD", false,-1);
    tracep->declBus(c+98,"ALUControlD", false,-1, 3,0);
    tracep->declBit(c+99,"ALUSrcD", false,-1);
    tracep->declBus(c+100,"ResultSrcD", false,-1, 1,0);
    tracep->declBit(c+101,"MemWriteD", false,-1);
    tracep->declBus(c+102,"modeBU", false,-1, 2,0);
    tracep->declBit(c+103,"ZeroE", false,-1);
    tracep->declBit(c+104,"MemReadD", false,-1);
    tracep->declBit(c+105,"MemReadE", false,-1);
    tracep->declBit(c+106,"JumpD", false,-1);
    tracep->declBit(c+107,"JumpE", false,-1);
    tracep->declBit(c+108,"BranchD", false,-1);
    tracep->declBit(c+109,"BranchE", false,-1);
    tracep->declBus(c+110,"RD1", false,-1, 31,0);
    tracep->declBus(c+111,"RD2", false,-1, 31,0);
    tracep->declBus(c+112,"ALUResult", false,-1, 31,0);
    tracep->declBus(c+113,"RD", false,-1, 31,0);
    tracep->declBus(c+114,"Result", false,-1, 31,0);
    tracep->declBus(c+115,"SrcA", false,-1, 31,0);
    tracep->declBus(c+116,"SrcB", false,-1, 31,0);
    tracep->declBus(c+117,"Rs1D", false,-1, 4,0);
    tracep->declBus(c+118,"Rs2D", false,-1, 4,0);
    tracep->declBus(c+119,"RdD", false,-1, 4,0);
    tracep->declBus(c+120,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+121,"Rs2E", false,-1, 4,0);
    tracep->declBus(c+122,"ResultW", false,-1, 31,0);
    tracep->declBus(c+123,"SrcBE", false,-1, 31,0);
    tracep->declBus(c+124,"ForwardAE", false,-1, 1,0);
    tracep->declBus(c+125,"ForwardBE", false,-1, 1,0);
    tracep->declBit(c+126,"flush", false,-1);
    tracep->declBit(c+127,"stall", false,-1);
    tracep->declBit(c+128,"flushBranch", false,-1);
    tracep->declBit(c+129,"BPU_Src", false,-1);
    tracep->declBus(c+130,"PC_predict", false,-1, 31,0);
    tracep->declBus(c+131,"PC_next", false,-1, 31,0);
    tracep->pushNamePrefix("BPU_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+132,"sel", false,-1);
    tracep->declBus(c+133,"in0", false,-1, 31,0);
    tracep->declBus(c+134,"in1", false,-1, 31,0);
    tracep->declBus(c+135,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("PC_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+136,"ZeroE", false,-1);
    tracep->declBit(c+137,"JumpE", false,-1);
    tracep->declBit(c+138,"BranchE", false,-1);
    tracep->declBus(c+139,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+140,"ALUResult", false,-1, 31,0);
    tracep->declBus(c+141,"PCTarget", false,-1, 31,0);
    tracep->declBus(c+142,"PC", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("alu ");
    tracep->declBus(c+374,"CONTROL_WIDTH", false,-1, 31,0);
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+143,"SrcA", false,-1, 31,0);
    tracep->declBus(c+144,"SrcB", false,-1, 31,0);
    tracep->declBus(c+145,"ALUctrl", false,-1, 3,0);
    tracep->declBus(c+146,"ALUResult", false,-1, 31,0);
    tracep->declBit(c+147,"ZeroE", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("alu_SrcBE_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+148,"sel", false,-1);
    tracep->declBus(c+149,"in0", false,-1, 31,0);
    tracep->declBus(c+150,"in1", false,-1, 31,0);
    tracep->declBus(c+151,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("branch_prediction_unit ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+152,"clk", false,-1);
    tracep->declBus(c+153,"RD", false,-1, 31,0);
    tracep->declBus(c+154,"PCF", false,-1, 31,0);
    tracep->declBit(c+155,"ZeroE", false,-1);
    tracep->declBit(c+156,"BranchE", false,-1);
    tracep->declBit(c+157,"flushBranch", false,-1);
    tracep->declBus(c+158,"PCBPU", false,-1, 31,0);
    tracep->declBit(c+159,"PCBPUSrc", false,-1);
    tracep->declBus(c+160,"forwardJumpCounter", false,-1, 1,0);
    tracep->declBus(c+161,"backwardJumpCounter", false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("control_unit ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+162,"InstrD", false,-1, 31,0);
    tracep->declBus(c+163,"ResultSrcD", false,-1, 1,0);
    tracep->declBit(c+164,"MemWriteD", false,-1);
    tracep->declBit(c+165,"JumpD", false,-1);
    tracep->declBit(c+166,"BranchD", false,-1);
    tracep->declBus(c+167,"ALUControlD", false,-1, 3,0);
    tracep->declBit(c+168,"ALUSrcD", false,-1);
    tracep->declBus(c+169,"ImmSrcD", false,-1, 2,0);
    tracep->declBit(c+170,"RegWriteD", false,-1);
    tracep->declBus(c+171,"modeBUD", false,-1, 2,0);
    tracep->declBit(c+172,"MemReadD", false,-1);
    tracep->declBus(c+173,"op", false,-1, 6,0);
    tracep->declBus(c+174,"funct3", false,-1, 14,12);
    tracep->declBit(c+175,"funct7", false,-1);
    tracep->declBus(c+176,"ALUOp", false,-1, 1,0);
    tracep->declBit(c+177,"Store", false,-1);
    tracep->declBit(c+178,"Load", false,-1);
    tracep->pushNamePrefix("alu_decoder ");
    tracep->declBus(c+179,"ALUOp", false,-1, 1,0);
    tracep->declBit(c+180,"op", false,-1);
    tracep->declBus(c+181,"funct3", false,-1, 2,0);
    tracep->declBit(c+182,"funct7", false,-1);
    tracep->declBus(c+183,"ALUControl", false,-1, 3,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("data_memory ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+184,"modeBU", false,-1, 2,0);
    tracep->declBus(c+185,"ResultSrc", false,-1, 1,0);
    tracep->declBit(c+186,"clk", false,-1);
    tracep->declBus(c+187,"A", false,-1, 31,0);
    tracep->declBus(c+188,"WD", false,-1, 31,0);
    tracep->declBit(c+189,"trigger", false,-1);
    tracep->declBit(c+190,"WE", false,-1);
    tracep->declBus(c+191,"RD", false,-1, 31,0);
    tracep->declBus(c+192,"Result", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("forwardAE_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+193,"sel", false,-1, 1,0);
    tracep->declBus(c+194,"in0", false,-1, 31,0);
    tracep->declBus(c+195,"in1", false,-1, 31,0);
    tracep->declBus(c+196,"in2", false,-1, 31,0);
    tracep->declBus(c+197,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("forwardBE_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+198,"sel", false,-1, 1,0);
    tracep->declBus(c+199,"in0", false,-1, 31,0);
    tracep->declBus(c+200,"in1", false,-1, 31,0);
    tracep->declBus(c+201,"in2", false,-1, 31,0);
    tracep->declBus(c+202,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("hazard_unit ");
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+203,"RdM", false,-1, 4,0);
    tracep->declBus(c+204,"RdW", false,-1, 4,0);
    tracep->declBus(c+205,"RdE", false,-1, 4,0);
    tracep->declBus(c+206,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+207,"Rs2E", false,-1, 4,0);
    tracep->declBit(c+208,"RegWriteM", false,-1);
    tracep->declBit(c+209,"RegWriteW", false,-1);
    tracep->declBit(c+210,"MemReadE", false,-1);
    tracep->declBit(c+211,"flushBranch", false,-1);
    tracep->declBus(c+212,"ForwardAE", false,-1, 1,0);
    tracep->declBus(c+213,"ForwardBE", false,-1, 1,0);
    tracep->declBit(c+214,"stall", false,-1);
    tracep->declBit(c+215,"flush", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instruction_memory ");
    tracep->declBus(c+373,"ADDRESS_WIDTH", false,-1, 31,0);
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+216,"PC", false,-1, 31,0);
    tracep->declBus(c+217,"instr", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_DE ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+218,"clk", false,-1);
    tracep->declBit(c+219,"flush", false,-1);
    tracep->declBit(c+220,"MemReadD", false,-1);
    tracep->declBit(c+221,"MemReadE", false,-1);
    tracep->declBit(c+222,"RegWriteD", false,-1);
    tracep->declBit(c+223,"RegWriteE", false,-1);
    tracep->declBus(c+224,"ResultSrcD", false,-1, 1,0);
    tracep->declBus(c+225,"ResultSrcE", false,-1, 1,0);
    tracep->declBit(c+226,"MemWriteD", false,-1);
    tracep->declBit(c+227,"MemWriteE", false,-1);
    tracep->declBit(c+228,"JumpD", false,-1);
    tracep->declBit(c+229,"JumpE", false,-1);
    tracep->declBit(c+230,"BranchD", false,-1);
    tracep->declBit(c+231,"BranchE", false,-1);
    tracep->declBus(c+232,"ALUControlD", false,-1, 3,0);
    tracep->declBus(c+233,"ALUControlE", false,-1, 3,0);
    tracep->declBit(c+234,"ALUSrcD", false,-1);
    tracep->declBit(c+235,"ALUSrcE", false,-1);
    tracep->declBus(c+236,"RD1", false,-1, 31,0);
    tracep->declBus(c+237,"RD1E", false,-1, 31,0);
    tracep->declBus(c+238,"RD2", false,-1, 31,0);
    tracep->declBus(c+239,"RD2E", false,-1, 31,0);
    tracep->declBus(c+240,"PCD", false,-1, 31,0);
    tracep->declBus(c+241,"PCE", false,-1, 31,0);
    tracep->declBus(c+242,"Rs1D", false,-1, 4,0);
    tracep->declBus(c+243,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+244,"Rs2D", false,-1, 4,0);
    tracep->declBus(c+245,"Rs2E", false,-1, 4,0);
    tracep->declBus(c+246,"RdD", false,-1, 4,0);
    tracep->declBus(c+247,"RdE", false,-1, 4,0);
    tracep->declBus(c+248,"ExtImmD", false,-1, 31,0);
    tracep->declBus(c+249,"ExtImmE", false,-1, 31,0);
    tracep->declBus(c+250,"PCPlus4D", false,-1, 31,0);
    tracep->declBus(c+251,"PCPlus4E", false,-1, 31,0);
    tracep->declBus(c+252,"modeBUD", false,-1, 2,0);
    tracep->declBus(c+253,"modeBUE", false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_EM ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+254,"clk", false,-1);
    tracep->declBit(c+255,"RegWriteE", false,-1);
    tracep->declBit(c+256,"RegWriteM", false,-1);
    tracep->declBus(c+257,"ResultSrcE", false,-1, 1,0);
    tracep->declBus(c+258,"ResultSrcM", false,-1, 1,0);
    tracep->declBit(c+259,"MemWriteE", false,-1);
    tracep->declBit(c+260,"MemWriteM", false,-1);
    tracep->declBus(c+261,"ALUResult", false,-1, 31,0);
    tracep->declBus(c+262,"ALUResultM", false,-1, 31,0);
    tracep->declBus(c+263,"WriteDataE", false,-1, 31,0);
    tracep->declBus(c+264,"WriteDataM", false,-1, 31,0);
    tracep->declBus(c+265,"RdE", false,-1, 4,0);
    tracep->declBus(c+266,"RdM", false,-1, 4,0);
    tracep->declBus(c+267,"PCPlus4E", false,-1, 31,0);
    tracep->declBus(c+268,"PCPlus4M", false,-1, 31,0);
    tracep->declBus(c+269,"modeBUE", false,-1, 2,0);
    tracep->declBus(c+270,"modeBUM", false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_FD ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+271,"clk", false,-1);
    tracep->declBit(c+272,"flush", false,-1);
    tracep->declBit(c+273,"stall", false,-1);
    tracep->declBus(c+274,"RD", false,-1, 31,0);
    tracep->declBus(c+275,"InstrD", false,-1, 31,0);
    tracep->declBus(c+276,"PCF", false,-1, 31,0);
    tracep->declBus(c+277,"PCD", false,-1, 31,0);
    tracep->declBus(c+278,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+279,"PCPlus4D", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_MW ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+280,"clk", false,-1);
    tracep->declBit(c+281,"RegWriteM", false,-1);
    tracep->declBit(c+282,"RegWriteW", false,-1);
    tracep->declBus(c+283,"ResultSrcM", false,-1, 1,0);
    tracep->declBus(c+284,"ResultSrcW", false,-1, 1,0);
    tracep->declBus(c+285,"ALUResultM", false,-1, 31,0);
    tracep->declBus(c+286,"ALUResultW", false,-1, 31,0);
    tracep->declBus(c+287,"RD", false,-1, 31,0);
    tracep->declBus(c+288,"ReadDataW", false,-1, 31,0);
    tracep->declBus(c+289,"RdM", false,-1, 4,0);
    tracep->declBus(c+290,"RdW", false,-1, 4,0);
    tracep->declBus(c+291,"PCPlus4M", false,-1, 31,0);
    tracep->declBus(c+292,"PCPlus4W", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("program_counter ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+293,"clk", false,-1);
    tracep->declBit(c+294,"rst", false,-1);
    tracep->declBus(c+295,"PC", false,-1, 31,0);
    tracep->declBit(c+296,"stall", false,-1);
    tracep->declBus(c+297,"PCF", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("regfile ");
    tracep->declBus(c+375,"ADDRESS_WIDTH", false,-1, 31,0);
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+298,"clk", false,-1);
    tracep->declBus(c+299,"AD1", false,-1, 4,0);
    tracep->declBus(c+300,"AD2", false,-1, 4,0);
    tracep->declBus(c+301,"AD3", false,-1, 4,0);
    tracep->declBit(c+302,"WE3", false,-1);
    tracep->declBus(c+303,"WD3", false,-1, 31,0);
    tracep->declBus(c+304,"RD1", false,-1, 31,0);
    tracep->declBus(c+305,"RD2", false,-1, 31,0);
    tracep->declBus(c+306,"a0", false,-1, 31,0);
    tracep->declBus(c+307,"a1", false,-1, 31,0);
    tracep->declBus(c+308,"a2", false,-1, 31,0);
    tracep->declBus(c+309,"a3", false,-1, 31,0);
    tracep->declBus(c+310,"a4", false,-1, 31,0);
    tracep->declBus(c+311,"a5", false,-1, 31,0);
    tracep->declBus(c+312,"a6", false,-1, 31,0);
    tracep->declBus(c+313,"a7", false,-1, 31,0);
    tracep->declBus(c+314,"t0", false,-1, 31,0);
    tracep->declBus(c+315,"t1", false,-1, 31,0);
    tracep->declBus(c+316,"t2", false,-1, 31,0);
    tracep->declBus(c+317,"t3", false,-1, 31,0);
    tracep->declBus(c+318,"t4", false,-1, 31,0);
    tracep->declBus(c+319,"t5", false,-1, 31,0);
    tracep->declBus(c+320,"t6", false,-1, 31,0);
    tracep->declBus(c+321,"s0", false,-1, 31,0);
    tracep->declBus(c+322,"s1", false,-1, 31,0);
    tracep->declBus(c+323,"s2", false,-1, 31,0);
    tracep->declBus(c+324,"s3", false,-1, 31,0);
    tracep->declBus(c+325,"s4", false,-1, 31,0);
    tracep->declBus(c+326,"s5", false,-1, 31,0);
    tracep->declBus(c+327,"s6", false,-1, 31,0);
    tracep->declBus(c+328,"s7", false,-1, 31,0);
    tracep->declBus(c+329,"s8", false,-1, 31,0);
    tracep->declBus(c+330,"s9", false,-1, 31,0);
    tracep->declBus(c+331,"s10", false,-1, 31,0);
    tracep->declBus(c+332,"s11", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+333+i*1,"registerfile_array", true,(i+0), 31,0);
    }
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("regfile_mux ");
    tracep->declBus(c+373,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+365,"sel", false,-1, 1,0);
    tracep->declBus(c+366,"in0", false,-1, 31,0);
    tracep->declBus(c+367,"in1", false,-1, 31,0);
    tracep->declBus(c+368,"in2", false,-1, 31,0);
    tracep->declBus(c+369,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("sign_extend ");
    tracep->declBus(c+373,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+370,"ImmSrc", false,-1, 2,0);
    tracep->declBus(c+371,"ImmInput", false,-1, 31,0);
    tracep->declBus(c+372,"ImmExt", false,-1, 31,0);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP____024unit__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP____024unit__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+376,"TAG_MSB", false,-1, 31,0);
    tracep->declBus(c+377,"TAG_LSB", false,-1, 31,0);
    tracep->declBus(c+378,"SETS", false,-1, 31,0);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
    tracep->pushNamePrefix("$unit ");
    Vtop___024root__trace_init_sub__TOP____024unit__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->clk));
    bufp->fullBit(oldp+2,(vlSelf->rst));
    bufp->fullBit(oldp+3,(vlSelf->trigger));
    bufp->fullIData(oldp+4,(vlSelf->a0),32);
    bufp->fullIData(oldp+5,(vlSelf->a1),32);
    bufp->fullIData(oldp+6,(vlSelf->a2),32);
    bufp->fullIData(oldp+7,(vlSelf->a3),32);
    bufp->fullIData(oldp+8,(vlSelf->a4),32);
    bufp->fullIData(oldp+9,(vlSelf->a5),32);
    bufp->fullIData(oldp+10,(vlSelf->a6),32);
    bufp->fullIData(oldp+11,(vlSelf->a7),32);
    bufp->fullIData(oldp+12,(vlSelf->t0),32);
    bufp->fullIData(oldp+13,(vlSelf->t1),32);
    bufp->fullIData(oldp+14,(vlSelf->t2),32);
    bufp->fullIData(oldp+15,(vlSelf->t3),32);
    bufp->fullIData(oldp+16,(vlSelf->t4),32);
    bufp->fullIData(oldp+17,(vlSelf->t5),32);
    bufp->fullIData(oldp+18,(vlSelf->t6),32);
    bufp->fullIData(oldp+19,(vlSelf->s0),32);
    bufp->fullIData(oldp+20,(vlSelf->s1),32);
    bufp->fullIData(oldp+21,(vlSelf->s2),32);
    bufp->fullIData(oldp+22,(vlSelf->s3),32);
    bufp->fullIData(oldp+23,(vlSelf->s4),32);
    bufp->fullIData(oldp+24,(vlSelf->s5),32);
    bufp->fullIData(oldp+25,(vlSelf->s6),32);
    bufp->fullIData(oldp+26,(vlSelf->s7),32);
    bufp->fullIData(oldp+27,(vlSelf->s8),32);
    bufp->fullIData(oldp+28,(vlSelf->s9),32);
    bufp->fullIData(oldp+29,(vlSelf->s10),32);
    bufp->fullIData(oldp+30,(vlSelf->s11),32);
    bufp->fullBit(oldp+31,(vlSelf->top__DOT__clk));
    bufp->fullBit(oldp+32,(vlSelf->top__DOT__rst));
    bufp->fullBit(oldp+33,(vlSelf->top__DOT__trigger));
    bufp->fullIData(oldp+34,(vlSelf->top__DOT__a0),32);
    bufp->fullIData(oldp+35,(vlSelf->top__DOT__a1),32);
    bufp->fullIData(oldp+36,(vlSelf->top__DOT__a2),32);
    bufp->fullIData(oldp+37,(vlSelf->top__DOT__a3),32);
    bufp->fullIData(oldp+38,(vlSelf->top__DOT__a4),32);
    bufp->fullIData(oldp+39,(vlSelf->top__DOT__a5),32);
    bufp->fullIData(oldp+40,(vlSelf->top__DOT__a6),32);
    bufp->fullIData(oldp+41,(vlSelf->top__DOT__a7),32);
    bufp->fullIData(oldp+42,(vlSelf->top__DOT__t0),32);
    bufp->fullIData(oldp+43,(vlSelf->top__DOT__t1),32);
    bufp->fullIData(oldp+44,(vlSelf->top__DOT__t2),32);
    bufp->fullIData(oldp+45,(vlSelf->top__DOT__t3),32);
    bufp->fullIData(oldp+46,(vlSelf->top__DOT__t4),32);
    bufp->fullIData(oldp+47,(vlSelf->top__DOT__t5),32);
    bufp->fullIData(oldp+48,(vlSelf->top__DOT__t6),32);
    bufp->fullIData(oldp+49,(vlSelf->top__DOT__s0),32);
    bufp->fullIData(oldp+50,(vlSelf->top__DOT__s1),32);
    bufp->fullIData(oldp+51,(vlSelf->top__DOT__s2),32);
    bufp->fullIData(oldp+52,(vlSelf->top__DOT__s3),32);
    bufp->fullIData(oldp+53,(vlSelf->top__DOT__s4),32);
    bufp->fullIData(oldp+54,(vlSelf->top__DOT__s5),32);
    bufp->fullIData(oldp+55,(vlSelf->top__DOT__s6),32);
    bufp->fullIData(oldp+56,(vlSelf->top__DOT__s7),32);
    bufp->fullIData(oldp+57,(vlSelf->top__DOT__s8),32);
    bufp->fullIData(oldp+58,(vlSelf->top__DOT__s9),32);
    bufp->fullIData(oldp+59,(vlSelf->top__DOT__s10),32);
    bufp->fullIData(oldp+60,(vlSelf->top__DOT__s11),32);
    bufp->fullIData(oldp+61,(vlSelf->top__DOT__PCF),32);
    bufp->fullIData(oldp+62,(vlSelf->top__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+63,(vlSelf->top__DOT__PC),32);
    bufp->fullIData(oldp+64,(vlSelf->top__DOT__InstrF),32);
    bufp->fullIData(oldp+65,(vlSelf->top__DOT__PCD),32);
    bufp->fullIData(oldp+66,(vlSelf->top__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+67,(vlSelf->top__DOT__InstrD),32);
    bufp->fullIData(oldp+68,(vlSelf->top__DOT__RD1E),32);
    bufp->fullIData(oldp+69,(vlSelf->top__DOT__RD2E),32);
    bufp->fullIData(oldp+70,(vlSelf->top__DOT__PCE),32);
    bufp->fullIData(oldp+71,(vlSelf->top__DOT__PCPlus4E),32);
    bufp->fullCData(oldp+72,(vlSelf->top__DOT__RdE),5);
    bufp->fullBit(oldp+73,(vlSelf->top__DOT__RegWriteE));
    bufp->fullBit(oldp+74,(vlSelf->top__DOT__ALUSrcE));
    bufp->fullBit(oldp+75,(vlSelf->top__DOT__MemWriteE));
    bufp->fullCData(oldp+76,(vlSelf->top__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+77,(vlSelf->top__DOT__ALUControlE),4);
    bufp->fullCData(oldp+78,(vlSelf->top__DOT__modeBUE),3);
    bufp->fullIData(oldp+79,(vlSelf->top__DOT__WriteDataE),32);
    bufp->fullIData(oldp+80,(vlSelf->top__DOT__ALUResultM),32);
    bufp->fullIData(oldp+81,(vlSelf->top__DOT__WriteDataM),32);
    bufp->fullCData(oldp+82,(vlSelf->top__DOT__RdM),5);
    bufp->fullBit(oldp+83,(vlSelf->top__DOT__RegWriteM));
    bufp->fullBit(oldp+84,(vlSelf->top__DOT__MemWriteM));
    bufp->fullCData(oldp+85,(vlSelf->top__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+86,(vlSelf->top__DOT__modeBUM),3);
    bufp->fullIData(oldp+87,(vlSelf->top__DOT__PCPlus4M),32);
    bufp->fullIData(oldp+88,(vlSelf->top__DOT__ALUResultW),32);
    bufp->fullIData(oldp+89,(vlSelf->top__DOT__ReadDataW),32);
    bufp->fullCData(oldp+90,(vlSelf->top__DOT__RdW),5);
    bufp->fullBit(oldp+91,(vlSelf->top__DOT__RegWriteW));
    bufp->fullCData(oldp+92,(vlSelf->top__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+93,(vlSelf->top__DOT__PCPlus4W),32);
    bufp->fullIData(oldp+94,(vlSelf->top__DOT__ExtImmD),32);
    bufp->fullIData(oldp+95,(vlSelf->top__DOT__ExtImmE),32);
    bufp->fullCData(oldp+96,(vlSelf->top__DOT__ImmSrcD),3);
    bufp->fullBit(oldp+97,(vlSelf->top__DOT__RegWriteD));
    bufp->fullCData(oldp+98,(vlSelf->top__DOT__ALUControlD),4);
    bufp->fullBit(oldp+99,(vlSelf->top__DOT__ALUSrcD));
    bufp->fullCData(oldp+100,(vlSelf->top__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+101,(vlSelf->top__DOT__MemWriteD));
    bufp->fullCData(oldp+102,(vlSelf->top__DOT__modeBU),3);
    bufp->fullBit(oldp+103,(vlSelf->top__DOT__ZeroE));
    bufp->fullBit(oldp+104,(vlSelf->top__DOT__MemReadD));
    bufp->fullBit(oldp+105,(vlSelf->top__DOT__MemReadE));
    bufp->fullBit(oldp+106,(vlSelf->top__DOT__JumpD));
    bufp->fullBit(oldp+107,(vlSelf->top__DOT__JumpE));
    bufp->fullBit(oldp+108,(vlSelf->top__DOT__BranchD));
    bufp->fullBit(oldp+109,(vlSelf->top__DOT__BranchE));
    bufp->fullIData(oldp+110,(vlSelf->top__DOT__RD1),32);
    bufp->fullIData(oldp+111,(vlSelf->top__DOT__RD2),32);
    bufp->fullIData(oldp+112,(vlSelf->top__DOT__ALUResult),32);
    bufp->fullIData(oldp+113,(vlSelf->top__DOT__RD),32);
    bufp->fullIData(oldp+114,(vlSelf->top__DOT__Result),32);
    bufp->fullIData(oldp+115,(vlSelf->top__DOT__SrcA),32);
    bufp->fullIData(oldp+116,(vlSelf->top__DOT__SrcB),32);
    bufp->fullCData(oldp+117,(vlSelf->top__DOT__Rs1D),5);
    bufp->fullCData(oldp+118,(vlSelf->top__DOT__Rs2D),5);
    bufp->fullCData(oldp+119,(vlSelf->top__DOT__RdD),5);
    bufp->fullCData(oldp+120,(vlSelf->top__DOT__Rs1E),5);
    bufp->fullCData(oldp+121,(vlSelf->top__DOT__Rs2E),5);
    bufp->fullIData(oldp+122,(vlSelf->top__DOT__ResultW),32);
    bufp->fullIData(oldp+123,(vlSelf->top__DOT__SrcBE),32);
    bufp->fullCData(oldp+124,(vlSelf->top__DOT__ForwardAE),2);
    bufp->fullCData(oldp+125,(vlSelf->top__DOT__ForwardBE),2);
    bufp->fullBit(oldp+126,(vlSelf->top__DOT__flush));
    bufp->fullBit(oldp+127,(vlSelf->top__DOT__stall));
    bufp->fullBit(oldp+128,(vlSelf->top__DOT__flushBranch));
    bufp->fullBit(oldp+129,(vlSelf->top__DOT__BPU_Src));
    bufp->fullIData(oldp+130,(vlSelf->top__DOT__PC_predict),32);
    bufp->fullIData(oldp+131,(vlSelf->top__DOT__PC_next),32);
    bufp->fullBit(oldp+132,(vlSelf->top__DOT__BPU_mux__DOT__sel));
    bufp->fullIData(oldp+133,(vlSelf->top__DOT__BPU_mux__DOT__in0),32);
    bufp->fullIData(oldp+134,(vlSelf->top__DOT__BPU_mux__DOT__in1),32);
    bufp->fullIData(oldp+135,(vlSelf->top__DOT__BPU_mux__DOT__out),32);
    bufp->fullBit(oldp+136,(vlSelf->top__DOT__PC_mux__DOT__ZeroE));
    bufp->fullBit(oldp+137,(vlSelf->top__DOT__PC_mux__DOT__JumpE));
    bufp->fullBit(oldp+138,(vlSelf->top__DOT__PC_mux__DOT__BranchE));
    bufp->fullIData(oldp+139,(vlSelf->top__DOT__PC_mux__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+140,(vlSelf->top__DOT__PC_mux__DOT__ALUResult),32);
    bufp->fullIData(oldp+141,(vlSelf->top__DOT__PC_mux__DOT__PCTarget),32);
    bufp->fullIData(oldp+142,(vlSelf->top__DOT__PC_mux__DOT__PC),32);
    bufp->fullIData(oldp+143,(vlSelf->top__DOT__alu__DOT__SrcA),32);
    bufp->fullIData(oldp+144,(vlSelf->top__DOT__alu__DOT__SrcB),32);
    bufp->fullCData(oldp+145,(vlSelf->top__DOT__alu__DOT__ALUctrl),4);
    bufp->fullIData(oldp+146,(vlSelf->top__DOT__alu__DOT__ALUResult),32);
    bufp->fullBit(oldp+147,(vlSelf->top__DOT__alu__DOT__ZeroE));
    bufp->fullBit(oldp+148,(vlSelf->top__DOT__alu_SrcBE_mux__DOT__sel));
    bufp->fullIData(oldp+149,(vlSelf->top__DOT__alu_SrcBE_mux__DOT__in0),32);
    bufp->fullIData(oldp+150,(vlSelf->top__DOT__alu_SrcBE_mux__DOT__in1),32);
    bufp->fullIData(oldp+151,(vlSelf->top__DOT__alu_SrcBE_mux__DOT__out),32);
    bufp->fullBit(oldp+152,(vlSelf->top__DOT__branch_prediction_unit__DOT__clk));
    bufp->fullIData(oldp+153,(vlSelf->top__DOT__branch_prediction_unit__DOT__RD),32);
    bufp->fullIData(oldp+154,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCF),32);
    bufp->fullBit(oldp+155,(vlSelf->top__DOT__branch_prediction_unit__DOT__ZeroE));
    bufp->fullBit(oldp+156,(vlSelf->top__DOT__branch_prediction_unit__DOT__BranchE));
    bufp->fullBit(oldp+157,(vlSelf->top__DOT__branch_prediction_unit__DOT__flushBranch));
    bufp->fullIData(oldp+158,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCBPU),32);
    bufp->fullBit(oldp+159,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCBPUSrc));
    bufp->fullCData(oldp+160,(vlSelf->top__DOT__branch_prediction_unit__DOT__forwardJumpCounter),2);
    bufp->fullCData(oldp+161,(vlSelf->top__DOT__branch_prediction_unit__DOT__backwardJumpCounter),2);
    bufp->fullIData(oldp+162,(vlSelf->top__DOT__control_unit__DOT__InstrD),32);
    bufp->fullCData(oldp+163,(vlSelf->top__DOT__control_unit__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+164,(vlSelf->top__DOT__control_unit__DOT__MemWriteD));
    bufp->fullBit(oldp+165,(vlSelf->top__DOT__control_unit__DOT__JumpD));
    bufp->fullBit(oldp+166,(vlSelf->top__DOT__control_unit__DOT__BranchD));
    bufp->fullCData(oldp+167,(vlSelf->top__DOT__control_unit__DOT__ALUControlD),4);
    bufp->fullBit(oldp+168,(vlSelf->top__DOT__control_unit__DOT__ALUSrcD));
    bufp->fullCData(oldp+169,(vlSelf->top__DOT__control_unit__DOT__ImmSrcD),3);
    bufp->fullBit(oldp+170,(vlSelf->top__DOT__control_unit__DOT__RegWriteD));
    bufp->fullCData(oldp+171,(vlSelf->top__DOT__control_unit__DOT__modeBUD),3);
    bufp->fullBit(oldp+172,(vlSelf->top__DOT__control_unit__DOT__MemReadD));
    bufp->fullCData(oldp+173,(vlSelf->top__DOT__control_unit__DOT__op),7);
    bufp->fullCData(oldp+174,(vlSelf->top__DOT__control_unit__DOT__funct3),3);
    bufp->fullBit(oldp+175,(vlSelf->top__DOT__control_unit__DOT__funct7));
    bufp->fullCData(oldp+176,(vlSelf->top__DOT__control_unit__DOT__ALUOp),2);
    bufp->fullBit(oldp+177,(vlSelf->top__DOT__control_unit__DOT__Store));
    bufp->fullBit(oldp+178,(vlSelf->top__DOT__control_unit__DOT__Load));
    bufp->fullCData(oldp+179,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__ALUOp),2);
    bufp->fullBit(oldp+180,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__op));
    bufp->fullCData(oldp+181,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__funct3),3);
    bufp->fullBit(oldp+182,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__funct7));
    bufp->fullCData(oldp+183,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__ALUControl),4);
    bufp->fullCData(oldp+184,(vlSelf->top__DOT__data_memory__DOT__modeBU),3);
    bufp->fullCData(oldp+185,(vlSelf->top__DOT__data_memory__DOT__ResultSrc),2);
    bufp->fullBit(oldp+186,(vlSelf->top__DOT__data_memory__DOT__clk));
    bufp->fullIData(oldp+187,(vlSelf->top__DOT__data_memory__DOT__A),32);
    bufp->fullIData(oldp+188,(vlSelf->top__DOT__data_memory__DOT__WD),32);
    bufp->fullBit(oldp+189,(vlSelf->top__DOT__data_memory__DOT__trigger));
    bufp->fullBit(oldp+190,(vlSelf->top__DOT__data_memory__DOT__WE));
    bufp->fullIData(oldp+191,(vlSelf->top__DOT__data_memory__DOT__RD),32);
    bufp->fullIData(oldp+192,(vlSelf->top__DOT__data_memory__DOT__Result),32);
    bufp->fullCData(oldp+193,(vlSelf->top__DOT__forwardAE_mux__DOT__sel),2);
    bufp->fullIData(oldp+194,(vlSelf->top__DOT__forwardAE_mux__DOT__in0),32);
    bufp->fullIData(oldp+195,(vlSelf->top__DOT__forwardAE_mux__DOT__in1),32);
    bufp->fullIData(oldp+196,(vlSelf->top__DOT__forwardAE_mux__DOT__in2),32);
    bufp->fullIData(oldp+197,(vlSelf->top__DOT__forwardAE_mux__DOT__out),32);
    bufp->fullCData(oldp+198,(vlSelf->top__DOT__forwardBE_mux__DOT__sel),2);
    bufp->fullIData(oldp+199,(vlSelf->top__DOT__forwardBE_mux__DOT__in0),32);
    bufp->fullIData(oldp+200,(vlSelf->top__DOT__forwardBE_mux__DOT__in1),32);
    bufp->fullIData(oldp+201,(vlSelf->top__DOT__forwardBE_mux__DOT__in2),32);
    bufp->fullIData(oldp+202,(vlSelf->top__DOT__forwardBE_mux__DOT__out),32);
    bufp->fullCData(oldp+203,(vlSelf->top__DOT__hazard_unit__DOT__RdM),5);
    bufp->fullCData(oldp+204,(vlSelf->top__DOT__hazard_unit__DOT__RdW),5);
    bufp->fullCData(oldp+205,(vlSelf->top__DOT__hazard_unit__DOT__RdE),5);
    bufp->fullCData(oldp+206,(vlSelf->top__DOT__hazard_unit__DOT__Rs1E),5);
    bufp->fullCData(oldp+207,(vlSelf->top__DOT__hazard_unit__DOT__Rs2E),5);
    bufp->fullBit(oldp+208,(vlSelf->top__DOT__hazard_unit__DOT__RegWriteM));
    bufp->fullBit(oldp+209,(vlSelf->top__DOT__hazard_unit__DOT__RegWriteW));
    bufp->fullBit(oldp+210,(vlSelf->top__DOT__hazard_unit__DOT__MemReadE));
    bufp->fullBit(oldp+211,(vlSelf->top__DOT__hazard_unit__DOT__flushBranch));
    bufp->fullCData(oldp+212,(vlSelf->top__DOT__hazard_unit__DOT__ForwardAE),2);
    bufp->fullCData(oldp+213,(vlSelf->top__DOT__hazard_unit__DOT__ForwardBE),2);
    bufp->fullBit(oldp+214,(vlSelf->top__DOT__hazard_unit__DOT__stall));
    bufp->fullBit(oldp+215,(vlSelf->top__DOT__hazard_unit__DOT__flush));
    bufp->fullIData(oldp+216,(vlSelf->top__DOT__instruction_memory__DOT__PC),32);
    bufp->fullIData(oldp+217,(vlSelf->top__DOT__instruction_memory__DOT__instr),32);
    bufp->fullBit(oldp+218,(vlSelf->top__DOT__pipeline_DE__DOT__clk));
    bufp->fullBit(oldp+219,(vlSelf->top__DOT__pipeline_DE__DOT__flush));
    bufp->fullBit(oldp+220,(vlSelf->top__DOT__pipeline_DE__DOT__MemReadD));
    bufp->fullBit(oldp+221,(vlSelf->top__DOT__pipeline_DE__DOT__MemReadE));
    bufp->fullBit(oldp+222,(vlSelf->top__DOT__pipeline_DE__DOT__RegWriteD));
    bufp->fullBit(oldp+223,(vlSelf->top__DOT__pipeline_DE__DOT__RegWriteE));
    bufp->fullCData(oldp+224,(vlSelf->top__DOT__pipeline_DE__DOT__ResultSrcD),2);
    bufp->fullCData(oldp+225,(vlSelf->top__DOT__pipeline_DE__DOT__ResultSrcE),2);
    bufp->fullBit(oldp+226,(vlSelf->top__DOT__pipeline_DE__DOT__MemWriteD));
    bufp->fullBit(oldp+227,(vlSelf->top__DOT__pipeline_DE__DOT__MemWriteE));
    bufp->fullBit(oldp+228,(vlSelf->top__DOT__pipeline_DE__DOT__JumpD));
    bufp->fullBit(oldp+229,(vlSelf->top__DOT__pipeline_DE__DOT__JumpE));
    bufp->fullBit(oldp+230,(vlSelf->top__DOT__pipeline_DE__DOT__BranchD));
    bufp->fullBit(oldp+231,(vlSelf->top__DOT__pipeline_DE__DOT__BranchE));
    bufp->fullCData(oldp+232,(vlSelf->top__DOT__pipeline_DE__DOT__ALUControlD),4);
    bufp->fullCData(oldp+233,(vlSelf->top__DOT__pipeline_DE__DOT__ALUControlE),4);
    bufp->fullBit(oldp+234,(vlSelf->top__DOT__pipeline_DE__DOT__ALUSrcD));
    bufp->fullBit(oldp+235,(vlSelf->top__DOT__pipeline_DE__DOT__ALUSrcE));
    bufp->fullIData(oldp+236,(vlSelf->top__DOT__pipeline_DE__DOT__RD1),32);
    bufp->fullIData(oldp+237,(vlSelf->top__DOT__pipeline_DE__DOT__RD1E),32);
    bufp->fullIData(oldp+238,(vlSelf->top__DOT__pipeline_DE__DOT__RD2),32);
    bufp->fullIData(oldp+239,(vlSelf->top__DOT__pipeline_DE__DOT__RD2E),32);
    bufp->fullIData(oldp+240,(vlSelf->top__DOT__pipeline_DE__DOT__PCD),32);
    bufp->fullIData(oldp+241,(vlSelf->top__DOT__pipeline_DE__DOT__PCE),32);
    bufp->fullCData(oldp+242,(vlSelf->top__DOT__pipeline_DE__DOT__Rs1D),5);
    bufp->fullCData(oldp+243,(vlSelf->top__DOT__pipeline_DE__DOT__Rs1E),5);
    bufp->fullCData(oldp+244,(vlSelf->top__DOT__pipeline_DE__DOT__Rs2D),5);
    bufp->fullCData(oldp+245,(vlSelf->top__DOT__pipeline_DE__DOT__Rs2E),5);
    bufp->fullCData(oldp+246,(vlSelf->top__DOT__pipeline_DE__DOT__RdD),5);
    bufp->fullCData(oldp+247,(vlSelf->top__DOT__pipeline_DE__DOT__RdE),5);
    bufp->fullIData(oldp+248,(vlSelf->top__DOT__pipeline_DE__DOT__ExtImmD),32);
    bufp->fullIData(oldp+249,(vlSelf->top__DOT__pipeline_DE__DOT__ExtImmE),32);
    bufp->fullIData(oldp+250,(vlSelf->top__DOT__pipeline_DE__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+251,(vlSelf->top__DOT__pipeline_DE__DOT__PCPlus4E),32);
    bufp->fullCData(oldp+252,(vlSelf->top__DOT__pipeline_DE__DOT__modeBUD),3);
    bufp->fullCData(oldp+253,(vlSelf->top__DOT__pipeline_DE__DOT__modeBUE),3);
    bufp->fullBit(oldp+254,(vlSelf->top__DOT__pipeline_EM__DOT__clk));
    bufp->fullBit(oldp+255,(vlSelf->top__DOT__pipeline_EM__DOT__RegWriteE));
    bufp->fullBit(oldp+256,(vlSelf->top__DOT__pipeline_EM__DOT__RegWriteM));
    bufp->fullCData(oldp+257,(vlSelf->top__DOT__pipeline_EM__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+258,(vlSelf->top__DOT__pipeline_EM__DOT__ResultSrcM),2);
    bufp->fullBit(oldp+259,(vlSelf->top__DOT__pipeline_EM__DOT__MemWriteE));
    bufp->fullBit(oldp+260,(vlSelf->top__DOT__pipeline_EM__DOT__MemWriteM));
    bufp->fullIData(oldp+261,(vlSelf->top__DOT__pipeline_EM__DOT__ALUResult),32);
    bufp->fullIData(oldp+262,(vlSelf->top__DOT__pipeline_EM__DOT__ALUResultM),32);
    bufp->fullIData(oldp+263,(vlSelf->top__DOT__pipeline_EM__DOT__WriteDataE),32);
    bufp->fullIData(oldp+264,(vlSelf->top__DOT__pipeline_EM__DOT__WriteDataM),32);
    bufp->fullCData(oldp+265,(vlSelf->top__DOT__pipeline_EM__DOT__RdE),5);
    bufp->fullCData(oldp+266,(vlSelf->top__DOT__pipeline_EM__DOT__RdM),5);
    bufp->fullIData(oldp+267,(vlSelf->top__DOT__pipeline_EM__DOT__PCPlus4E),32);
    bufp->fullIData(oldp+268,(vlSelf->top__DOT__pipeline_EM__DOT__PCPlus4M),32);
    bufp->fullCData(oldp+269,(vlSelf->top__DOT__pipeline_EM__DOT__modeBUE),3);
    bufp->fullCData(oldp+270,(vlSelf->top__DOT__pipeline_EM__DOT__modeBUM),3);
    bufp->fullBit(oldp+271,(vlSelf->top__DOT__pipeline_FD__DOT__clk));
    bufp->fullBit(oldp+272,(vlSelf->top__DOT__pipeline_FD__DOT__flush));
    bufp->fullBit(oldp+273,(vlSelf->top__DOT__pipeline_FD__DOT__stall));
    bufp->fullIData(oldp+274,(vlSelf->top__DOT__pipeline_FD__DOT__RD),32);
    bufp->fullIData(oldp+275,(vlSelf->top__DOT__pipeline_FD__DOT__InstrD),32);
    bufp->fullIData(oldp+276,(vlSelf->top__DOT__pipeline_FD__DOT__PCF),32);
    bufp->fullIData(oldp+277,(vlSelf->top__DOT__pipeline_FD__DOT__PCD),32);
    bufp->fullIData(oldp+278,(vlSelf->top__DOT__pipeline_FD__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+279,(vlSelf->top__DOT__pipeline_FD__DOT__PCPlus4D),32);
    bufp->fullBit(oldp+280,(vlSelf->top__DOT__pipeline_MW__DOT__clk));
    bufp->fullBit(oldp+281,(vlSelf->top__DOT__pipeline_MW__DOT__RegWriteM));
    bufp->fullBit(oldp+282,(vlSelf->top__DOT__pipeline_MW__DOT__RegWriteW));
    bufp->fullCData(oldp+283,(vlSelf->top__DOT__pipeline_MW__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+284,(vlSelf->top__DOT__pipeline_MW__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+285,(vlSelf->top__DOT__pipeline_MW__DOT__ALUResultM),32);
    bufp->fullIData(oldp+286,(vlSelf->top__DOT__pipeline_MW__DOT__ALUResultW),32);
    bufp->fullIData(oldp+287,(vlSelf->top__DOT__pipeline_MW__DOT__RD),32);
    bufp->fullIData(oldp+288,(vlSelf->top__DOT__pipeline_MW__DOT__ReadDataW),32);
    bufp->fullCData(oldp+289,(vlSelf->top__DOT__pipeline_MW__DOT__RdM),5);
    bufp->fullCData(oldp+290,(vlSelf->top__DOT__pipeline_MW__DOT__RdW),5);
    bufp->fullIData(oldp+291,(vlSelf->top__DOT__pipeline_MW__DOT__PCPlus4M),32);
    bufp->fullIData(oldp+292,(vlSelf->top__DOT__pipeline_MW__DOT__PCPlus4W),32);
    bufp->fullBit(oldp+293,(vlSelf->top__DOT__program_counter__DOT__clk));
    bufp->fullBit(oldp+294,(vlSelf->top__DOT__program_counter__DOT__rst));
    bufp->fullIData(oldp+295,(vlSelf->top__DOT__program_counter__DOT__PC),32);
    bufp->fullBit(oldp+296,(vlSelf->top__DOT__program_counter__DOT__stall));
    bufp->fullIData(oldp+297,(vlSelf->top__DOT__program_counter__DOT__PCF),32);
    bufp->fullBit(oldp+298,(vlSelf->top__DOT__regfile__DOT__clk));
    bufp->fullCData(oldp+299,(vlSelf->top__DOT__regfile__DOT__AD1),5);
    bufp->fullCData(oldp+300,(vlSelf->top__DOT__regfile__DOT__AD2),5);
    bufp->fullCData(oldp+301,(vlSelf->top__DOT__regfile__DOT__AD3),5);
    bufp->fullBit(oldp+302,(vlSelf->top__DOT__regfile__DOT__WE3));
    bufp->fullIData(oldp+303,(vlSelf->top__DOT__regfile__DOT__WD3),32);
    bufp->fullIData(oldp+304,(vlSelf->top__DOT__regfile__DOT__RD1),32);
    bufp->fullIData(oldp+305,(vlSelf->top__DOT__regfile__DOT__RD2),32);
    bufp->fullIData(oldp+306,(vlSelf->top__DOT__regfile__DOT__a0),32);
    bufp->fullIData(oldp+307,(vlSelf->top__DOT__regfile__DOT__a1),32);
    bufp->fullIData(oldp+308,(vlSelf->top__DOT__regfile__DOT__a2),32);
    bufp->fullIData(oldp+309,(vlSelf->top__DOT__regfile__DOT__a3),32);
    bufp->fullIData(oldp+310,(vlSelf->top__DOT__regfile__DOT__a4),32);
    bufp->fullIData(oldp+311,(vlSelf->top__DOT__regfile__DOT__a5),32);
    bufp->fullIData(oldp+312,(vlSelf->top__DOT__regfile__DOT__a6),32);
    bufp->fullIData(oldp+313,(vlSelf->top__DOT__regfile__DOT__a7),32);
    bufp->fullIData(oldp+314,(vlSelf->top__DOT__regfile__DOT__t0),32);
    bufp->fullIData(oldp+315,(vlSelf->top__DOT__regfile__DOT__t1),32);
    bufp->fullIData(oldp+316,(vlSelf->top__DOT__regfile__DOT__t2),32);
    bufp->fullIData(oldp+317,(vlSelf->top__DOT__regfile__DOT__t3),32);
    bufp->fullIData(oldp+318,(vlSelf->top__DOT__regfile__DOT__t4),32);
    bufp->fullIData(oldp+319,(vlSelf->top__DOT__regfile__DOT__t5),32);
    bufp->fullIData(oldp+320,(vlSelf->top__DOT__regfile__DOT__t6),32);
    bufp->fullIData(oldp+321,(vlSelf->top__DOT__regfile__DOT__s0),32);
    bufp->fullIData(oldp+322,(vlSelf->top__DOT__regfile__DOT__s1),32);
    bufp->fullIData(oldp+323,(vlSelf->top__DOT__regfile__DOT__s2),32);
    bufp->fullIData(oldp+324,(vlSelf->top__DOT__regfile__DOT__s3),32);
    bufp->fullIData(oldp+325,(vlSelf->top__DOT__regfile__DOT__s4),32);
    bufp->fullIData(oldp+326,(vlSelf->top__DOT__regfile__DOT__s5),32);
    bufp->fullIData(oldp+327,(vlSelf->top__DOT__regfile__DOT__s6),32);
    bufp->fullIData(oldp+328,(vlSelf->top__DOT__regfile__DOT__s7),32);
    bufp->fullIData(oldp+329,(vlSelf->top__DOT__regfile__DOT__s8),32);
    bufp->fullIData(oldp+330,(vlSelf->top__DOT__regfile__DOT__s9),32);
    bufp->fullIData(oldp+331,(vlSelf->top__DOT__regfile__DOT__s10),32);
    bufp->fullIData(oldp+332,(vlSelf->top__DOT__regfile__DOT__s11),32);
    bufp->fullIData(oldp+333,(vlSelf->top__DOT__regfile__DOT__registerfile_array[0]),32);
    bufp->fullIData(oldp+334,(vlSelf->top__DOT__regfile__DOT__registerfile_array[1]),32);
    bufp->fullIData(oldp+335,(vlSelf->top__DOT__regfile__DOT__registerfile_array[2]),32);
    bufp->fullIData(oldp+336,(vlSelf->top__DOT__regfile__DOT__registerfile_array[3]),32);
    bufp->fullIData(oldp+337,(vlSelf->top__DOT__regfile__DOT__registerfile_array[4]),32);
    bufp->fullIData(oldp+338,(vlSelf->top__DOT__regfile__DOT__registerfile_array[5]),32);
    bufp->fullIData(oldp+339,(vlSelf->top__DOT__regfile__DOT__registerfile_array[6]),32);
    bufp->fullIData(oldp+340,(vlSelf->top__DOT__regfile__DOT__registerfile_array[7]),32);
    bufp->fullIData(oldp+341,(vlSelf->top__DOT__regfile__DOT__registerfile_array[8]),32);
    bufp->fullIData(oldp+342,(vlSelf->top__DOT__regfile__DOT__registerfile_array[9]),32);
    bufp->fullIData(oldp+343,(vlSelf->top__DOT__regfile__DOT__registerfile_array[10]),32);
    bufp->fullIData(oldp+344,(vlSelf->top__DOT__regfile__DOT__registerfile_array[11]),32);
    bufp->fullIData(oldp+345,(vlSelf->top__DOT__regfile__DOT__registerfile_array[12]),32);
    bufp->fullIData(oldp+346,(vlSelf->top__DOT__regfile__DOT__registerfile_array[13]),32);
    bufp->fullIData(oldp+347,(vlSelf->top__DOT__regfile__DOT__registerfile_array[14]),32);
    bufp->fullIData(oldp+348,(vlSelf->top__DOT__regfile__DOT__registerfile_array[15]),32);
    bufp->fullIData(oldp+349,(vlSelf->top__DOT__regfile__DOT__registerfile_array[16]),32);
    bufp->fullIData(oldp+350,(vlSelf->top__DOT__regfile__DOT__registerfile_array[17]),32);
    bufp->fullIData(oldp+351,(vlSelf->top__DOT__regfile__DOT__registerfile_array[18]),32);
    bufp->fullIData(oldp+352,(vlSelf->top__DOT__regfile__DOT__registerfile_array[19]),32);
    bufp->fullIData(oldp+353,(vlSelf->top__DOT__regfile__DOT__registerfile_array[20]),32);
    bufp->fullIData(oldp+354,(vlSelf->top__DOT__regfile__DOT__registerfile_array[21]),32);
    bufp->fullIData(oldp+355,(vlSelf->top__DOT__regfile__DOT__registerfile_array[22]),32);
    bufp->fullIData(oldp+356,(vlSelf->top__DOT__regfile__DOT__registerfile_array[23]),32);
    bufp->fullIData(oldp+357,(vlSelf->top__DOT__regfile__DOT__registerfile_array[24]),32);
    bufp->fullIData(oldp+358,(vlSelf->top__DOT__regfile__DOT__registerfile_array[25]),32);
    bufp->fullIData(oldp+359,(vlSelf->top__DOT__regfile__DOT__registerfile_array[26]),32);
    bufp->fullIData(oldp+360,(vlSelf->top__DOT__regfile__DOT__registerfile_array[27]),32);
    bufp->fullIData(oldp+361,(vlSelf->top__DOT__regfile__DOT__registerfile_array[28]),32);
    bufp->fullIData(oldp+362,(vlSelf->top__DOT__regfile__DOT__registerfile_array[29]),32);
    bufp->fullIData(oldp+363,(vlSelf->top__DOT__regfile__DOT__registerfile_array[30]),32);
    bufp->fullIData(oldp+364,(vlSelf->top__DOT__regfile__DOT__registerfile_array[31]),32);
    bufp->fullCData(oldp+365,(vlSelf->top__DOT__regfile_mux__DOT__sel),2);
    bufp->fullIData(oldp+366,(vlSelf->top__DOT__regfile_mux__DOT__in0),32);
    bufp->fullIData(oldp+367,(vlSelf->top__DOT__regfile_mux__DOT__in1),32);
    bufp->fullIData(oldp+368,(vlSelf->top__DOT__regfile_mux__DOT__in2),32);
    bufp->fullIData(oldp+369,(vlSelf->top__DOT__regfile_mux__DOT__out),32);
    bufp->fullCData(oldp+370,(vlSelf->top__DOT__sign_extend__DOT__ImmSrc),3);
    bufp->fullIData(oldp+371,(vlSelf->top__DOT__sign_extend__DOT__ImmInput),32);
    bufp->fullIData(oldp+372,(vlSelf->top__DOT__sign_extend__DOT__ImmExt),32);
    bufp->fullIData(oldp+373,(0x20U),32);
    bufp->fullIData(oldp+374,(4U),32);
    bufp->fullIData(oldp+375,(5U),32);
    bufp->fullIData(oldp+376,(0x1fU),32);
    bufp->fullIData(oldp+377,(0xbU),32);
    bufp->fullIData(oldp+378,(0x100U),32);
}
