// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,"clk", false,-1);
    tracep->declBit(c+2,"rst", false,-1);
    tracep->declBit(c+3,"trigger", false,-1);
    tracep->declBus(c+4,"a0", false,-1, 31,0);
    tracep->declBus(c+5,"a1", false,-1, 31,0);
    tracep->declBus(c+6,"a2", false,-1, 31,0);
    tracep->declBus(c+7,"a3", false,-1, 31,0);
    tracep->declBus(c+8,"a4", false,-1, 31,0);
    tracep->declBus(c+9,"a5", false,-1, 31,0);
    tracep->declBus(c+10,"a6", false,-1, 31,0);
    tracep->declBus(c+11,"a7", false,-1, 31,0);
    tracep->declBus(c+12,"t0", false,-1, 31,0);
    tracep->declBus(c+13,"t1", false,-1, 31,0);
    tracep->declBus(c+14,"t2", false,-1, 31,0);
    tracep->declBus(c+15,"t3", false,-1, 31,0);
    tracep->declBus(c+16,"t4", false,-1, 31,0);
    tracep->declBus(c+17,"t5", false,-1, 31,0);
    tracep->declBus(c+18,"t6", false,-1, 31,0);
    tracep->declBus(c+19,"s0", false,-1, 31,0);
    tracep->declBus(c+20,"s1", false,-1, 31,0);
    tracep->declBus(c+21,"s2", false,-1, 31,0);
    tracep->declBus(c+22,"s3", false,-1, 31,0);
    tracep->declBus(c+23,"s4", false,-1, 31,0);
    tracep->declBus(c+24,"s5", false,-1, 31,0);
    tracep->declBus(c+25,"s6", false,-1, 31,0);
    tracep->declBus(c+26,"s7", false,-1, 31,0);
    tracep->declBus(c+27,"s8", false,-1, 31,0);
    tracep->declBus(c+28,"s9", false,-1, 31,0);
    tracep->declBus(c+29,"s10", false,-1, 31,0);
    tracep->declBus(c+30,"s11", false,-1, 31,0);
    tracep->pushNamePrefix("top ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+31,"clk", false,-1);
    tracep->declBit(c+32,"rst", false,-1);
    tracep->declBit(c+33,"trigger", false,-1);
    tracep->declBus(c+34,"a0", false,-1, 31,0);
    tracep->declBus(c+35,"a1", false,-1, 31,0);
    tracep->declBus(c+36,"a2", false,-1, 31,0);
    tracep->declBus(c+37,"a3", false,-1, 31,0);
    tracep->declBus(c+38,"a4", false,-1, 31,0);
    tracep->declBus(c+39,"a5", false,-1, 31,0);
    tracep->declBus(c+40,"a6", false,-1, 31,0);
    tracep->declBus(c+41,"a7", false,-1, 31,0);
    tracep->declBus(c+42,"t0", false,-1, 31,0);
    tracep->declBus(c+43,"t1", false,-1, 31,0);
    tracep->declBus(c+44,"t2", false,-1, 31,0);
    tracep->declBus(c+45,"t3", false,-1, 31,0);
    tracep->declBus(c+46,"t4", false,-1, 31,0);
    tracep->declBus(c+47,"t5", false,-1, 31,0);
    tracep->declBus(c+48,"t6", false,-1, 31,0);
    tracep->declBus(c+49,"s0", false,-1, 31,0);
    tracep->declBus(c+50,"s1", false,-1, 31,0);
    tracep->declBus(c+51,"s2", false,-1, 31,0);
    tracep->declBus(c+52,"s3", false,-1, 31,0);
    tracep->declBus(c+53,"s4", false,-1, 31,0);
    tracep->declBus(c+54,"s5", false,-1, 31,0);
    tracep->declBus(c+55,"s6", false,-1, 31,0);
    tracep->declBus(c+56,"s7", false,-1, 31,0);
    tracep->declBus(c+57,"s8", false,-1, 31,0);
    tracep->declBus(c+58,"s9", false,-1, 31,0);
    tracep->declBus(c+59,"s10", false,-1, 31,0);
    tracep->declBus(c+60,"s11", false,-1, 31,0);
    tracep->declBus(c+61,"PCF", false,-1, 31,0);
    tracep->declBus(c+62,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+63,"PC", false,-1, 31,0);
    tracep->declBus(c+64,"InstrF", false,-1, 31,0);
    tracep->declBus(c+65,"PCD", false,-1, 31,0);
    tracep->declBus(c+66,"PCPlus4D", false,-1, 31,0);
    tracep->declBus(c+67,"InstrD", false,-1, 31,0);
    tracep->declBus(c+68,"RD1E", false,-1, 31,0);
    tracep->declBus(c+69,"RD2E", false,-1, 31,0);
    tracep->declBus(c+70,"PCE", false,-1, 31,0);
    tracep->declBus(c+71,"PCPlus4E", false,-1, 31,0);
    tracep->declBit(c+72,"RegWriteE", false,-1);
    tracep->declBit(c+73,"ALUSrcE", false,-1);
    tracep->declBit(c+74,"MemWriteE", false,-1);
    tracep->declBus(c+75,"ResultSrcE", false,-1, 1,0);
    tracep->declBus(c+76,"ALUControlE", false,-1, 3,0);
    tracep->declBus(c+77,"modeBUE", false,-1, 2,0);
    tracep->declBus(c+78,"WriteDataE", false,-1, 31,0);
    tracep->declBit(c+79,"RegWriteM", false,-1);
    tracep->declBit(c+80,"MemWriteM", false,-1);
    tracep->declBus(c+81,"ResultSrcM", false,-1, 1,0);
    tracep->declBus(c+82,"modeAddrM", false,-1, 2,0);
    tracep->declBus(c+83,"ReadDataW", false,-1, 31,0);
    tracep->declBit(c+84,"RegWriteW", false,-1);
    tracep->declBus(c+85,"ResultSrcW", false,-1, 1,0);
    tracep->declBus(c+86,"PCPlus4W", false,-1, 31,0);
    tracep->declBus(c+87,"ExtImmD", false,-1, 31,0);
    tracep->declBus(c+88,"ExtImmE", false,-1, 31,0);
    tracep->declBus(c+89,"ImmSrc", false,-1, 2,0);
    tracep->declBit(c+90,"RegWriteD", false,-1);
    tracep->declBus(c+91,"ALUControlD", false,-1, 3,0);
    tracep->declBit(c+92,"ALUSrcD", false,-1);
    tracep->declBus(c+93,"ResultSrcD", false,-1, 1,0);
    tracep->declBit(c+94,"MemWriteD", false,-1);
    tracep->declBus(c+95,"modeBU", false,-1, 2,0);
    tracep->declBit(c+96,"ZeroE", false,-1);
    tracep->declBit(c+97,"MemReadD", false,-1);
    tracep->declBit(c+98,"MemReadE", false,-1);
    tracep->declBit(c+99,"JumpD", false,-1);
    tracep->declBit(c+100,"JumpE", false,-1);
    tracep->declBit(c+101,"BranchD", false,-1);
    tracep->declBit(c+102,"BranchE", false,-1);
    tracep->declBus(c+103,"RD1", false,-1, 31,0);
    tracep->declBus(c+104,"RD2", false,-1, 31,0);
    tracep->declBus(c+105,"RD", false,-1, 31,0);
    tracep->declBus(c+106,"Result", false,-1, 31,0);
    tracep->declBus(c+107,"SrcA", false,-1, 31,0);
    tracep->declBus(c+108,"SrcB", false,-1, 31,0);
    tracep->declBus(c+109,"Rs1D", false,-1, 4,0);
    tracep->declBus(c+110,"Rs2D", false,-1, 4,0);
    tracep->declBus(c+111,"RdD", false,-1, 4,0);
    tracep->declBus(c+112,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+113,"Rs2E", false,-1, 4,0);
    tracep->declBus(c+114,"ResultW", false,-1, 31,0);
    tracep->declBus(c+115,"SrcAE", false,-1, 31,0);
    tracep->declBus(c+116,"ForwardAE", false,-1, 1,0);
    tracep->declBus(c+117,"ForwardBE", false,-1, 1,0);
    tracep->declBit(c+118,"flush", false,-1);
    tracep->declBit(c+119,"stall", false,-1);
    tracep->declBit(c+120,"flushBranch", false,-1);
    tracep->declBit(c+121,"BPU_Src", false,-1);
    tracep->declBus(c+122,"PC_predict", false,-1, 31,0);
    tracep->declBus(c+123,"PC_next", false,-1, 31,0);
    tracep->declBit(c+124,"RdM", false,-1);
    tracep->declBit(c+125,"RdW", false,-1);
    tracep->declBit(c+126,"RdE", false,-1);
    tracep->declBit(c+127,"Zero", false,-1);
    tracep->declBit(c+371,"ALUResult", false,-1);
    tracep->declBit(c+372,"ImmSrcD", false,-1);
    tracep->declBit(c+128,"ALUResultM", false,-1);
    tracep->declBit(c+129,"ALUResultE", false,-1);
    tracep->declBit(c+130,"WriteDataM", false,-1);
    tracep->declBit(c+131,"ALUResultW", false,-1);
    tracep->declBit(c+373,"modeAddrD", false,-1);
    tracep->declBit(c+132,"modeAddrE", false,-1);
    tracep->declBit(c+133,"PCPlus4M", false,-1);
    tracep->pushNamePrefix("BPU_mux ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+134,"sel", false,-1);
    tracep->declBus(c+135,"in0", false,-1, 31,0);
    tracep->declBus(c+136,"in1", false,-1, 31,0);
    tracep->declBus(c+137,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("PC_mux ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+138,"ZeroE", false,-1);
    tracep->declBit(c+139,"JumpE", false,-1);
    tracep->declBit(c+140,"BranchE", false,-1);
    tracep->declBus(c+141,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+142,"ALUResult", false,-1, 31,0);
    tracep->declBus(c+143,"PCTarget", false,-1, 31,0);
    tracep->declBus(c+144,"PC", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("alu ");
    tracep->declBus(c+374,"CONTROL_WIDTH", false,-1, 31,0);
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+145,"SrcA", false,-1, 31,0);
    tracep->declBus(c+146,"SrcB", false,-1, 31,0);
    tracep->declBus(c+147,"ALUctrl", false,-1, 3,0);
    tracep->declBus(c+148,"ALUResult", false,-1, 31,0);
    tracep->declBit(c+127,"ZeroE", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("branch_prediction_unit ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+149,"clk", false,-1);
    tracep->declBus(c+150,"RD", false,-1, 31,0);
    tracep->declBus(c+151,"PCF", false,-1, 31,0);
    tracep->declBit(c+152,"ZeroE", false,-1);
    tracep->declBit(c+153,"BranchE", false,-1);
    tracep->declBit(c+154,"flushBranch", false,-1);
    tracep->declBus(c+155,"PCBPU", false,-1, 31,0);
    tracep->declBit(c+156,"PCBPUSrc", false,-1);
    tracep->declBus(c+157,"forwardJumpCounter", false,-1, 1,0);
    tracep->declBus(c+158,"backwardJumpCounter", false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("control_unit ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+159,"InstrD", false,-1, 31,0);
    tracep->declBus(c+160,"ResultSrcD", false,-1, 1,0);
    tracep->declBit(c+161,"MemWriteD", false,-1);
    tracep->declBit(c+162,"JumpD", false,-1);
    tracep->declBit(c+163,"BranchD", false,-1);
    tracep->declBus(c+164,"ALUControlD", false,-1, 3,0);
    tracep->declBit(c+165,"ALUSrcD", false,-1);
    tracep->declBus(c+166,"ImmSrcD", false,-1, 2,0);
    tracep->declBit(c+167,"RegWriteD", false,-1);
    tracep->declBus(c+168,"modeAddr", false,-1, 2,0);
    tracep->declBit(c+169,"MemReadD", false,-1);
    tracep->declBus(c+170,"op", false,-1, 6,0);
    tracep->declBus(c+171,"funct3", false,-1, 14,12);
    tracep->declBit(c+172,"funct7", false,-1);
    tracep->declBus(c+173,"ALUOp", false,-1, 1,0);
    tracep->declBit(c+174,"Store", false,-1);
    tracep->declBit(c+175,"Load", false,-1);
    tracep->pushNamePrefix("alu_decoder ");
    tracep->declBus(c+176,"ALUOp", false,-1, 1,0);
    tracep->declBit(c+177,"op", false,-1);
    tracep->declBus(c+178,"funct3", false,-1, 2,0);
    tracep->declBit(c+179,"funct7", false,-1);
    tracep->declBus(c+180,"ALUControl", false,-1, 3,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("data_memory ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+181,"modeAddr", false,-1, 2,0);
    tracep->declBus(c+182,"ResultSrc", false,-1, 1,0);
    tracep->declBit(c+183,"clk", false,-1);
    tracep->declBus(c+184,"A", false,-1, 31,0);
    tracep->declBus(c+185,"WD", false,-1, 31,0);
    tracep->declBit(c+186,"trigger", false,-1);
    tracep->declBit(c+187,"WE", false,-1);
    tracep->declBus(c+188,"RD", false,-1, 31,0);
    tracep->declBus(c+189,"Result", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("forwardAE_mux ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+190,"sel", false,-1, 1,0);
    tracep->declBus(c+191,"in0", false,-1, 31,0);
    tracep->declBus(c+192,"in1", false,-1, 31,0);
    tracep->declBus(c+193,"in2", false,-1, 31,0);
    tracep->declBus(c+194,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("forwardBE_mux ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+195,"sel", false,-1, 1,0);
    tracep->declBus(c+196,"in0", false,-1, 31,0);
    tracep->declBus(c+197,"in1", false,-1, 31,0);
    tracep->declBus(c+198,"in2", false,-1, 31,0);
    tracep->declBus(c+199,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("hazard_unit ");
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+200,"RdM", false,-1, 4,0);
    tracep->declBus(c+201,"RdW", false,-1, 4,0);
    tracep->declBus(c+202,"RdE", false,-1, 4,0);
    tracep->declBus(c+203,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+204,"Rs2E", false,-1, 4,0);
    tracep->declBit(c+205,"RegWriteM", false,-1);
    tracep->declBit(c+206,"RegWriteW", false,-1);
    tracep->declBit(c+207,"MemReadE", false,-1);
    tracep->declBit(c+208,"flushBranch", false,-1);
    tracep->declBus(c+209,"ForwardAE", false,-1, 1,0);
    tracep->declBus(c+210,"ForwardBE", false,-1, 1,0);
    tracep->declBit(c+211,"stall", false,-1);
    tracep->declBit(c+212,"flush", false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instruction_memory ");
    tracep->declBus(c+370,"ADDRESS_WIDTH", false,-1, 31,0);
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+213,"PC", false,-1, 31,0);
    tracep->declBus(c+214,"instr", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_DE ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+215,"clk", false,-1);
    tracep->declBit(c+216,"flush", false,-1);
    tracep->declBit(c+217,"MemReadD", false,-1);
    tracep->declBit(c+218,"MemReadE", false,-1);
    tracep->declBit(c+219,"RegWriteD", false,-1);
    tracep->declBit(c+220,"RegWriteE", false,-1);
    tracep->declBus(c+221,"ResultSrcD", false,-1, 1,0);
    tracep->declBus(c+222,"ResultSrcE", false,-1, 1,0);
    tracep->declBit(c+223,"MemWriteD", false,-1);
    tracep->declBit(c+224,"MemWriteE", false,-1);
    tracep->declBit(c+225,"JumpD", false,-1);
    tracep->declBit(c+226,"JumpE", false,-1);
    tracep->declBit(c+227,"BranchD", false,-1);
    tracep->declBit(c+228,"BranchE", false,-1);
    tracep->declBus(c+229,"ALUControlD", false,-1, 3,0);
    tracep->declBus(c+230,"ALUControlE", false,-1, 3,0);
    tracep->declBit(c+231,"ALUSrcD", false,-1);
    tracep->declBit(c+232,"ALUSrcE", false,-1);
    tracep->declBus(c+233,"RD1", false,-1, 31,0);
    tracep->declBus(c+234,"RD1E", false,-1, 31,0);
    tracep->declBus(c+235,"RD2", false,-1, 31,0);
    tracep->declBus(c+236,"RD2E", false,-1, 31,0);
    tracep->declBus(c+237,"PCD", false,-1, 31,0);
    tracep->declBus(c+238,"PCE", false,-1, 31,0);
    tracep->declBus(c+239,"Rs1D", false,-1, 4,0);
    tracep->declBus(c+240,"Rs1E", false,-1, 4,0);
    tracep->declBus(c+241,"Rs2D", false,-1, 4,0);
    tracep->declBus(c+242,"Rs2E", false,-1, 4,0);
    tracep->declBus(c+243,"RdD", false,-1, 4,0);
    tracep->declBus(c+244,"RdE", false,-1, 4,0);
    tracep->declBus(c+245,"ExtImmD", false,-1, 31,0);
    tracep->declBus(c+246,"ExtImmE", false,-1, 31,0);
    tracep->declBus(c+247,"PCPlus4D", false,-1, 31,0);
    tracep->declBus(c+248,"PCPlus4E", false,-1, 31,0);
    tracep->declBus(c+249,"modeAddrD", false,-1, 2,0);
    tracep->declBus(c+250,"modeAddrE", false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_EM ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+251,"clk", false,-1);
    tracep->declBit(c+252,"RegWriteE", false,-1);
    tracep->declBit(c+253,"RegWriteM", false,-1);
    tracep->declBus(c+254,"ResultSrcE", false,-1, 1,0);
    tracep->declBus(c+255,"ResultSrcM", false,-1, 1,0);
    tracep->declBit(c+256,"MemWriteE", false,-1);
    tracep->declBit(c+257,"MemWriteM", false,-1);
    tracep->declBus(c+258,"ALUResultE", false,-1, 31,0);
    tracep->declBus(c+259,"ALUResultM", false,-1, 31,0);
    tracep->declBus(c+260,"WriteDataE", false,-1, 31,0);
    tracep->declBus(c+261,"WriteDataM", false,-1, 31,0);
    tracep->declBus(c+262,"RdE", false,-1, 4,0);
    tracep->declBus(c+263,"RdM", false,-1, 4,0);
    tracep->declBus(c+264,"PCPlus4E", false,-1, 31,0);
    tracep->declBus(c+265,"PCPlus4M", false,-1, 31,0);
    tracep->declBus(c+266,"modeAddrE", false,-1, 2,0);
    tracep->declBus(c+267,"modeAddrM", false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_FD ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+268,"clk", false,-1);
    tracep->declBit(c+269,"flush", false,-1);
    tracep->declBit(c+270,"stall", false,-1);
    tracep->declBus(c+271,"RD", false,-1, 31,0);
    tracep->declBus(c+272,"InstrD", false,-1, 31,0);
    tracep->declBus(c+273,"PCF", false,-1, 31,0);
    tracep->declBus(c+274,"PCD", false,-1, 31,0);
    tracep->declBus(c+275,"PCPlus4F", false,-1, 31,0);
    tracep->declBus(c+276,"PCPlus4D", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("pipeline_MW ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+375,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+277,"clk", false,-1);
    tracep->declBit(c+278,"RegWriteM", false,-1);
    tracep->declBit(c+279,"RegWriteW", false,-1);
    tracep->declBus(c+280,"ResultSrcM", false,-1, 1,0);
    tracep->declBus(c+281,"ResultSrcW", false,-1, 1,0);
    tracep->declBus(c+282,"ALUResultM", false,-1, 31,0);
    tracep->declBus(c+283,"ALUResultW", false,-1, 31,0);
    tracep->declBus(c+284,"RD", false,-1, 31,0);
    tracep->declBus(c+285,"ReadDataW", false,-1, 31,0);
    tracep->declBus(c+286,"RdM", false,-1, 4,0);
    tracep->declBus(c+287,"RdW", false,-1, 4,0);
    tracep->declBus(c+288,"PCPlus4M", false,-1, 31,0);
    tracep->declBus(c+289,"PCPlus4W", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("program_counter ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBit(c+290,"clk", false,-1);
    tracep->declBit(c+291,"rst", false,-1);
    tracep->declBus(c+292,"PC", false,-1, 31,0);
    tracep->declBit(c+293,"stall", false,-1);
    tracep->declBus(c+294,"PCF", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("regfile ");
    tracep->declBus(c+375,"ADDRESS_WIDTH", false,-1, 31,0);
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBit(c+295,"clk", false,-1);
    tracep->declBus(c+296,"AD1", false,-1, 4,0);
    tracep->declBus(c+297,"AD2", false,-1, 4,0);
    tracep->declBus(c+298,"AD3", false,-1, 4,0);
    tracep->declBit(c+299,"WE3", false,-1);
    tracep->declBus(c+300,"WD3", false,-1, 31,0);
    tracep->declBus(c+301,"RD1", false,-1, 31,0);
    tracep->declBus(c+302,"RD2", false,-1, 31,0);
    tracep->declBus(c+303,"a0", false,-1, 31,0);
    tracep->declBus(c+304,"a1", false,-1, 31,0);
    tracep->declBus(c+305,"a2", false,-1, 31,0);
    tracep->declBus(c+306,"a3", false,-1, 31,0);
    tracep->declBus(c+307,"a4", false,-1, 31,0);
    tracep->declBus(c+308,"a5", false,-1, 31,0);
    tracep->declBus(c+309,"a6", false,-1, 31,0);
    tracep->declBus(c+310,"a7", false,-1, 31,0);
    tracep->declBus(c+311,"t0", false,-1, 31,0);
    tracep->declBus(c+312,"t1", false,-1, 31,0);
    tracep->declBus(c+313,"t2", false,-1, 31,0);
    tracep->declBus(c+314,"t3", false,-1, 31,0);
    tracep->declBus(c+315,"t4", false,-1, 31,0);
    tracep->declBus(c+316,"t5", false,-1, 31,0);
    tracep->declBus(c+317,"t6", false,-1, 31,0);
    tracep->declBus(c+318,"s0", false,-1, 31,0);
    tracep->declBus(c+319,"s1", false,-1, 31,0);
    tracep->declBus(c+320,"s2", false,-1, 31,0);
    tracep->declBus(c+321,"s3", false,-1, 31,0);
    tracep->declBus(c+322,"s4", false,-1, 31,0);
    tracep->declBus(c+323,"s5", false,-1, 31,0);
    tracep->declBus(c+324,"s6", false,-1, 31,0);
    tracep->declBus(c+325,"s7", false,-1, 31,0);
    tracep->declBus(c+326,"s8", false,-1, 31,0);
    tracep->declBus(c+327,"s9", false,-1, 31,0);
    tracep->declBus(c+328,"s10", false,-1, 31,0);
    tracep->declBus(c+329,"s11", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+330+i*1,"registerfile_array", true,(i+0), 31,0);
    }
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("regfile_mux ");
    tracep->declBus(c+370,"WIDTH", false,-1, 31,0);
    tracep->declBus(c+362,"sel", false,-1, 1,0);
    tracep->declBus(c+363,"in0", false,-1, 31,0);
    tracep->declBus(c+364,"in1", false,-1, 31,0);
    tracep->declBus(c+365,"in2", false,-1, 31,0);
    tracep->declBus(c+366,"out", false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("sign_extend ");
    tracep->declBus(c+370,"DATA_WIDTH", false,-1, 31,0);
    tracep->declBus(c+367,"ImmSrc", false,-1, 2,0);
    tracep->declBus(c+368,"ImmInput", false,-1, 31,0);
    tracep->declBus(c+369,"ImmExt", false,-1, 31,0);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP____024unit__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP____024unit__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+376,"TAG_MSB", false,-1, 31,0);
    tracep->declBus(c+377,"TAG_LSB", false,-1, 31,0);
    tracep->declBus(c+378,"SETS", false,-1, 31,0);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
    tracep->pushNamePrefix("$unit ");
    Vtop___024root__trace_init_sub__TOP____024unit__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->clk));
    bufp->fullBit(oldp+2,(vlSelf->rst));
    bufp->fullBit(oldp+3,(vlSelf->trigger));
    bufp->fullIData(oldp+4,(vlSelf->a0),32);
    bufp->fullIData(oldp+5,(vlSelf->a1),32);
    bufp->fullIData(oldp+6,(vlSelf->a2),32);
    bufp->fullIData(oldp+7,(vlSelf->a3),32);
    bufp->fullIData(oldp+8,(vlSelf->a4),32);
    bufp->fullIData(oldp+9,(vlSelf->a5),32);
    bufp->fullIData(oldp+10,(vlSelf->a6),32);
    bufp->fullIData(oldp+11,(vlSelf->a7),32);
    bufp->fullIData(oldp+12,(vlSelf->t0),32);
    bufp->fullIData(oldp+13,(vlSelf->t1),32);
    bufp->fullIData(oldp+14,(vlSelf->t2),32);
    bufp->fullIData(oldp+15,(vlSelf->t3),32);
    bufp->fullIData(oldp+16,(vlSelf->t4),32);
    bufp->fullIData(oldp+17,(vlSelf->t5),32);
    bufp->fullIData(oldp+18,(vlSelf->t6),32);
    bufp->fullIData(oldp+19,(vlSelf->s0),32);
    bufp->fullIData(oldp+20,(vlSelf->s1),32);
    bufp->fullIData(oldp+21,(vlSelf->s2),32);
    bufp->fullIData(oldp+22,(vlSelf->s3),32);
    bufp->fullIData(oldp+23,(vlSelf->s4),32);
    bufp->fullIData(oldp+24,(vlSelf->s5),32);
    bufp->fullIData(oldp+25,(vlSelf->s6),32);
    bufp->fullIData(oldp+26,(vlSelf->s7),32);
    bufp->fullIData(oldp+27,(vlSelf->s8),32);
    bufp->fullIData(oldp+28,(vlSelf->s9),32);
    bufp->fullIData(oldp+29,(vlSelf->s10),32);
    bufp->fullIData(oldp+30,(vlSelf->s11),32);
    bufp->fullBit(oldp+31,(vlSelf->top__DOT__clk));
    bufp->fullBit(oldp+32,(vlSelf->top__DOT__rst));
    bufp->fullBit(oldp+33,(vlSelf->top__DOT__trigger));
    bufp->fullIData(oldp+34,(vlSelf->top__DOT__a0),32);
    bufp->fullIData(oldp+35,(vlSelf->top__DOT__a1),32);
    bufp->fullIData(oldp+36,(vlSelf->top__DOT__a2),32);
    bufp->fullIData(oldp+37,(vlSelf->top__DOT__a3),32);
    bufp->fullIData(oldp+38,(vlSelf->top__DOT__a4),32);
    bufp->fullIData(oldp+39,(vlSelf->top__DOT__a5),32);
    bufp->fullIData(oldp+40,(vlSelf->top__DOT__a6),32);
    bufp->fullIData(oldp+41,(vlSelf->top__DOT__a7),32);
    bufp->fullIData(oldp+42,(vlSelf->top__DOT__t0),32);
    bufp->fullIData(oldp+43,(vlSelf->top__DOT__t1),32);
    bufp->fullIData(oldp+44,(vlSelf->top__DOT__t2),32);
    bufp->fullIData(oldp+45,(vlSelf->top__DOT__t3),32);
    bufp->fullIData(oldp+46,(vlSelf->top__DOT__t4),32);
    bufp->fullIData(oldp+47,(vlSelf->top__DOT__t5),32);
    bufp->fullIData(oldp+48,(vlSelf->top__DOT__t6),32);
    bufp->fullIData(oldp+49,(vlSelf->top__DOT__s0),32);
    bufp->fullIData(oldp+50,(vlSelf->top__DOT__s1),32);
    bufp->fullIData(oldp+51,(vlSelf->top__DOT__s2),32);
    bufp->fullIData(oldp+52,(vlSelf->top__DOT__s3),32);
    bufp->fullIData(oldp+53,(vlSelf->top__DOT__s4),32);
    bufp->fullIData(oldp+54,(vlSelf->top__DOT__s5),32);
    bufp->fullIData(oldp+55,(vlSelf->top__DOT__s6),32);
    bufp->fullIData(oldp+56,(vlSelf->top__DOT__s7),32);
    bufp->fullIData(oldp+57,(vlSelf->top__DOT__s8),32);
    bufp->fullIData(oldp+58,(vlSelf->top__DOT__s9),32);
    bufp->fullIData(oldp+59,(vlSelf->top__DOT__s10),32);
    bufp->fullIData(oldp+60,(vlSelf->top__DOT__s11),32);
    bufp->fullIData(oldp+61,(vlSelf->top__DOT__PCF),32);
    bufp->fullIData(oldp+62,(vlSelf->top__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+63,(vlSelf->top__DOT__PC),32);
    bufp->fullIData(oldp+64,(vlSelf->top__DOT__InstrF),32);
    bufp->fullIData(oldp+65,(vlSelf->top__DOT__PCD),32);
    bufp->fullIData(oldp+66,(vlSelf->top__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+67,(vlSelf->top__DOT__InstrD),32);
    bufp->fullIData(oldp+68,(vlSelf->top__DOT__RD1E),32);
    bufp->fullIData(oldp+69,(vlSelf->top__DOT__RD2E),32);
    bufp->fullIData(oldp+70,(vlSelf->top__DOT__PCE),32);
    bufp->fullIData(oldp+71,(vlSelf->top__DOT__PCPlus4E),32);
    bufp->fullBit(oldp+72,(vlSelf->top__DOT__RegWriteE));
    bufp->fullBit(oldp+73,(vlSelf->top__DOT__ALUSrcE));
    bufp->fullBit(oldp+74,(vlSelf->top__DOT__MemWriteE));
    bufp->fullCData(oldp+75,(vlSelf->top__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+76,(vlSelf->top__DOT__ALUControlE),4);
    bufp->fullCData(oldp+77,(vlSelf->top__DOT__modeBUE),3);
    bufp->fullIData(oldp+78,(vlSelf->top__DOT__WriteDataE),32);
    bufp->fullBit(oldp+79,(vlSelf->top__DOT__RegWriteM));
    bufp->fullBit(oldp+80,(vlSelf->top__DOT__MemWriteM));
    bufp->fullCData(oldp+81,(vlSelf->top__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+82,(vlSelf->top__DOT__modeAddrM),3);
    bufp->fullIData(oldp+83,(vlSelf->top__DOT__ReadDataW),32);
    bufp->fullBit(oldp+84,(vlSelf->top__DOT__RegWriteW));
    bufp->fullCData(oldp+85,(vlSelf->top__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+86,(vlSelf->top__DOT__PCPlus4W),32);
    bufp->fullIData(oldp+87,(vlSelf->top__DOT__ExtImmD),32);
    bufp->fullIData(oldp+88,(vlSelf->top__DOT__ExtImmE),32);
    bufp->fullCData(oldp+89,(vlSelf->top__DOT__ImmSrc),3);
    bufp->fullBit(oldp+90,(vlSelf->top__DOT__RegWriteD));
    bufp->fullCData(oldp+91,(vlSelf->top__DOT__ALUControlD),4);
    bufp->fullBit(oldp+92,(vlSelf->top__DOT__ALUSrcD));
    bufp->fullCData(oldp+93,(vlSelf->top__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+94,(vlSelf->top__DOT__MemWriteD));
    bufp->fullCData(oldp+95,(vlSelf->top__DOT__modeBU),3);
    bufp->fullBit(oldp+96,(vlSelf->top__DOT__ZeroE));
    bufp->fullBit(oldp+97,(vlSelf->top__DOT__MemReadD));
    bufp->fullBit(oldp+98,(vlSelf->top__DOT__MemReadE));
    bufp->fullBit(oldp+99,(vlSelf->top__DOT__JumpD));
    bufp->fullBit(oldp+100,(vlSelf->top__DOT__JumpE));
    bufp->fullBit(oldp+101,(vlSelf->top__DOT__BranchD));
    bufp->fullBit(oldp+102,(vlSelf->top__DOT__BranchE));
    bufp->fullIData(oldp+103,(vlSelf->top__DOT__RD1),32);
    bufp->fullIData(oldp+104,(vlSelf->top__DOT__RD2),32);
    bufp->fullIData(oldp+105,(vlSelf->top__DOT__RD),32);
    bufp->fullIData(oldp+106,(vlSelf->top__DOT__Result),32);
    bufp->fullIData(oldp+107,(vlSelf->top__DOT__SrcA),32);
    bufp->fullIData(oldp+108,(vlSelf->top__DOT__SrcB),32);
    bufp->fullCData(oldp+109,(vlSelf->top__DOT__Rs1D),5);
    bufp->fullCData(oldp+110,(vlSelf->top__DOT__Rs2D),5);
    bufp->fullCData(oldp+111,(vlSelf->top__DOT__RdD),5);
    bufp->fullCData(oldp+112,(vlSelf->top__DOT__Rs1E),5);
    bufp->fullCData(oldp+113,(vlSelf->top__DOT__Rs2E),5);
    bufp->fullIData(oldp+114,(vlSelf->top__DOT__ResultW),32);
    bufp->fullIData(oldp+115,(vlSelf->top__DOT__SrcAE),32);
    bufp->fullCData(oldp+116,(vlSelf->top__DOT__ForwardAE),2);
    bufp->fullCData(oldp+117,(vlSelf->top__DOT__ForwardBE),2);
    bufp->fullBit(oldp+118,(vlSelf->top__DOT__flush));
    bufp->fullBit(oldp+119,(vlSelf->top__DOT__stall));
    bufp->fullBit(oldp+120,(vlSelf->top__DOT__flushBranch));
    bufp->fullBit(oldp+121,(vlSelf->top__DOT__BPU_Src));
    bufp->fullIData(oldp+122,(vlSelf->top__DOT__PC_predict),32);
    bufp->fullIData(oldp+123,(vlSelf->top__DOT__PC_next),32);
    bufp->fullBit(oldp+124,((1U & (IData)(vlSelf->top__DOT__pipeline_EM__DOT__RdM))));
    bufp->fullBit(oldp+125,((1U & (IData)(vlSelf->top__DOT__pipeline_MW__DOT__RdW))));
    bufp->fullBit(oldp+126,((1U & (IData)(vlSelf->top__DOT__pipeline_DE__DOT__RdE))));
    bufp->fullBit(oldp+127,(vlSelf->top__DOT__alu__DOT__ZeroE));
    bufp->fullBit(oldp+128,((1U & vlSelf->top__DOT__pipeline_EM__DOT__ALUResultM)));
    bufp->fullBit(oldp+129,((1U & vlSelf->top__DOT__alu__DOT__ALUResult)));
    bufp->fullBit(oldp+130,((1U & vlSelf->top__DOT__pipeline_EM__DOT__WriteDataM)));
    bufp->fullBit(oldp+131,((1U & vlSelf->top__DOT__pipeline_MW__DOT__ALUResultW)));
    bufp->fullBit(oldp+132,((1U & (IData)(vlSelf->top__DOT__pipeline_DE__DOT__modeAddrE))));
    bufp->fullBit(oldp+133,((1U & vlSelf->top__DOT__pipeline_EM__DOT__PCPlus4M)));
    bufp->fullBit(oldp+134,(vlSelf->top__DOT__BPU_mux__DOT__sel));
    bufp->fullIData(oldp+135,(vlSelf->top__DOT__BPU_mux__DOT__in0),32);
    bufp->fullIData(oldp+136,(vlSelf->top__DOT__BPU_mux__DOT__in1),32);
    bufp->fullIData(oldp+137,(vlSelf->top__DOT__BPU_mux__DOT__out),32);
    bufp->fullBit(oldp+138,(vlSelf->top__DOT__PC_mux__DOT__ZeroE));
    bufp->fullBit(oldp+139,(vlSelf->top__DOT__PC_mux__DOT__JumpE));
    bufp->fullBit(oldp+140,(vlSelf->top__DOT__PC_mux__DOT__BranchE));
    bufp->fullIData(oldp+141,(vlSelf->top__DOT__PC_mux__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+142,(vlSelf->top__DOT__PC_mux__DOT__ALUResult),32);
    bufp->fullIData(oldp+143,(vlSelf->top__DOT__PC_mux__DOT__PCTarget),32);
    bufp->fullIData(oldp+144,(vlSelf->top__DOT__PC_mux__DOT__PC),32);
    bufp->fullIData(oldp+145,(vlSelf->top__DOT__alu__DOT__SrcA),32);
    bufp->fullIData(oldp+146,(vlSelf->top__DOT__alu__DOT__SrcB),32);
    bufp->fullCData(oldp+147,(vlSelf->top__DOT__alu__DOT__ALUctrl),4);
    bufp->fullIData(oldp+148,(vlSelf->top__DOT__alu__DOT__ALUResult),32);
    bufp->fullBit(oldp+149,(vlSelf->top__DOT__branch_prediction_unit__DOT__clk));
    bufp->fullIData(oldp+150,(vlSelf->top__DOT__branch_prediction_unit__DOT__RD),32);
    bufp->fullIData(oldp+151,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCF),32);
    bufp->fullBit(oldp+152,(vlSelf->top__DOT__branch_prediction_unit__DOT__ZeroE));
    bufp->fullBit(oldp+153,(vlSelf->top__DOT__branch_prediction_unit__DOT__BranchE));
    bufp->fullBit(oldp+154,(vlSelf->top__DOT__branch_prediction_unit__DOT__flushBranch));
    bufp->fullIData(oldp+155,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCBPU),32);
    bufp->fullBit(oldp+156,(vlSelf->top__DOT__branch_prediction_unit__DOT__PCBPUSrc));
    bufp->fullCData(oldp+157,(vlSelf->top__DOT__branch_prediction_unit__DOT__forwardJumpCounter),2);
    bufp->fullCData(oldp+158,(vlSelf->top__DOT__branch_prediction_unit__DOT__backwardJumpCounter),2);
    bufp->fullIData(oldp+159,(vlSelf->top__DOT__control_unit__DOT__InstrD),32);
    bufp->fullCData(oldp+160,(vlSelf->top__DOT__control_unit__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+161,(vlSelf->top__DOT__control_unit__DOT__MemWriteD));
    bufp->fullBit(oldp+162,(vlSelf->top__DOT__control_unit__DOT__JumpD));
    bufp->fullBit(oldp+163,(vlSelf->top__DOT__control_unit__DOT__BranchD));
    bufp->fullCData(oldp+164,(vlSelf->top__DOT__control_unit__DOT__ALUControlD),4);
    bufp->fullBit(oldp+165,(vlSelf->top__DOT__control_unit__DOT__ALUSrcD));
    bufp->fullCData(oldp+166,(vlSelf->top__DOT__control_unit__DOT__ImmSrcD),3);
    bufp->fullBit(oldp+167,(vlSelf->top__DOT__control_unit__DOT__RegWriteD));
    bufp->fullCData(oldp+168,(vlSelf->top__DOT__control_unit__DOT__modeAddr),3);
    bufp->fullBit(oldp+169,(vlSelf->top__DOT__control_unit__DOT__MemReadD));
    bufp->fullCData(oldp+170,(vlSelf->top__DOT__control_unit__DOT__op),7);
    bufp->fullCData(oldp+171,(vlSelf->top__DOT__control_unit__DOT__funct3),3);
    bufp->fullBit(oldp+172,(vlSelf->top__DOT__control_unit__DOT__funct7));
    bufp->fullCData(oldp+173,(vlSelf->top__DOT__control_unit__DOT__ALUOp),2);
    bufp->fullBit(oldp+174,(vlSelf->top__DOT__control_unit__DOT__Store));
    bufp->fullBit(oldp+175,(vlSelf->top__DOT__control_unit__DOT__Load));
    bufp->fullCData(oldp+176,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__ALUOp),2);
    bufp->fullBit(oldp+177,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__op));
    bufp->fullCData(oldp+178,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__funct3),3);
    bufp->fullBit(oldp+179,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__funct7));
    bufp->fullCData(oldp+180,(vlSelf->top__DOT__control_unit__DOT__alu_decoder__DOT__ALUControl),4);
    bufp->fullCData(oldp+181,(vlSelf->top__DOT__data_memory__DOT__modeAddr),3);
    bufp->fullCData(oldp+182,(vlSelf->top__DOT__data_memory__DOT__ResultSrc),2);
    bufp->fullBit(oldp+183,(vlSelf->top__DOT__data_memory__DOT__clk));
    bufp->fullIData(oldp+184,(vlSelf->top__DOT__data_memory__DOT__A),32);
    bufp->fullIData(oldp+185,(vlSelf->top__DOT__data_memory__DOT__WD),32);
    bufp->fullBit(oldp+186,(vlSelf->top__DOT__data_memory__DOT__trigger));
    bufp->fullBit(oldp+187,(vlSelf->top__DOT__data_memory__DOT__WE));
    bufp->fullIData(oldp+188,(vlSelf->top__DOT__data_memory__DOT__RD),32);
    bufp->fullIData(oldp+189,(vlSelf->top__DOT__data_memory__DOT__Result),32);
    bufp->fullCData(oldp+190,(vlSelf->top__DOT__forwardAE_mux__DOT__sel),2);
    bufp->fullIData(oldp+191,(vlSelf->top__DOT__forwardAE_mux__DOT__in0),32);
    bufp->fullIData(oldp+192,(vlSelf->top__DOT__forwardAE_mux__DOT__in1),32);
    bufp->fullIData(oldp+193,(vlSelf->top__DOT__forwardAE_mux__DOT__in2),32);
    bufp->fullIData(oldp+194,(vlSelf->top__DOT__forwardAE_mux__DOT__out),32);
    bufp->fullCData(oldp+195,(vlSelf->top__DOT__forwardBE_mux__DOT__sel),2);
    bufp->fullIData(oldp+196,(vlSelf->top__DOT__forwardBE_mux__DOT__in0),32);
    bufp->fullIData(oldp+197,(vlSelf->top__DOT__forwardBE_mux__DOT__in1),32);
    bufp->fullIData(oldp+198,(vlSelf->top__DOT__forwardBE_mux__DOT__in2),32);
    bufp->fullIData(oldp+199,(vlSelf->top__DOT__forwardBE_mux__DOT__out),32);
    bufp->fullCData(oldp+200,(vlSelf->top__DOT__hazard_unit__DOT__RdM),5);
    bufp->fullCData(oldp+201,(vlSelf->top__DOT__hazard_unit__DOT__RdW),5);
    bufp->fullCData(oldp+202,(vlSelf->top__DOT__hazard_unit__DOT__RdE),5);
    bufp->fullCData(oldp+203,(vlSelf->top__DOT__hazard_unit__DOT__Rs1E),5);
    bufp->fullCData(oldp+204,(vlSelf->top__DOT__hazard_unit__DOT__Rs2E),5);
    bufp->fullBit(oldp+205,(vlSelf->top__DOT__hazard_unit__DOT__RegWriteM));
    bufp->fullBit(oldp+206,(vlSelf->top__DOT__hazard_unit__DOT__RegWriteW));
    bufp->fullBit(oldp+207,(vlSelf->top__DOT__hazard_unit__DOT__MemReadE));
    bufp->fullBit(oldp+208,(vlSelf->top__DOT__hazard_unit__DOT__flushBranch));
    bufp->fullCData(oldp+209,(vlSelf->top__DOT__hazard_unit__DOT__ForwardAE),2);
    bufp->fullCData(oldp+210,(vlSelf->top__DOT__hazard_unit__DOT__ForwardBE),2);
    bufp->fullBit(oldp+211,(vlSelf->top__DOT__hazard_unit__DOT__stall));
    bufp->fullBit(oldp+212,(vlSelf->top__DOT__hazard_unit__DOT__flush));
    bufp->fullIData(oldp+213,(vlSelf->top__DOT__instruction_memory__DOT__PC),32);
    bufp->fullIData(oldp+214,(vlSelf->top__DOT__instruction_memory__DOT__instr),32);
    bufp->fullBit(oldp+215,(vlSelf->top__DOT__pipeline_DE__DOT__clk));
    bufp->fullBit(oldp+216,(vlSelf->top__DOT__pipeline_DE__DOT__flush));
    bufp->fullBit(oldp+217,(vlSelf->top__DOT__pipeline_DE__DOT__MemReadD));
    bufp->fullBit(oldp+218,(vlSelf->top__DOT__pipeline_DE__DOT__MemReadE));
    bufp->fullBit(oldp+219,(vlSelf->top__DOT__pipeline_DE__DOT__RegWriteD));
    bufp->fullBit(oldp+220,(vlSelf->top__DOT__pipeline_DE__DOT__RegWriteE));
    bufp->fullCData(oldp+221,(vlSelf->top__DOT__pipeline_DE__DOT__ResultSrcD),2);
    bufp->fullCData(oldp+222,(vlSelf->top__DOT__pipeline_DE__DOT__ResultSrcE),2);
    bufp->fullBit(oldp+223,(vlSelf->top__DOT__pipeline_DE__DOT__MemWriteD));
    bufp->fullBit(oldp+224,(vlSelf->top__DOT__pipeline_DE__DOT__MemWriteE));
    bufp->fullBit(oldp+225,(vlSelf->top__DOT__pipeline_DE__DOT__JumpD));
    bufp->fullBit(oldp+226,(vlSelf->top__DOT__pipeline_DE__DOT__JumpE));
    bufp->fullBit(oldp+227,(vlSelf->top__DOT__pipeline_DE__DOT__BranchD));
    bufp->fullBit(oldp+228,(vlSelf->top__DOT__pipeline_DE__DOT__BranchE));
    bufp->fullCData(oldp+229,(vlSelf->top__DOT__pipeline_DE__DOT__ALUControlD),4);
    bufp->fullCData(oldp+230,(vlSelf->top__DOT__pipeline_DE__DOT__ALUControlE),4);
    bufp->fullBit(oldp+231,(vlSelf->top__DOT__pipeline_DE__DOT__ALUSrcD));
    bufp->fullBit(oldp+232,(vlSelf->top__DOT__pipeline_DE__DOT__ALUSrcE));
    bufp->fullIData(oldp+233,(vlSelf->top__DOT__pipeline_DE__DOT__RD1),32);
    bufp->fullIData(oldp+234,(vlSelf->top__DOT__pipeline_DE__DOT__RD1E),32);
    bufp->fullIData(oldp+235,(vlSelf->top__DOT__pipeline_DE__DOT__RD2),32);
    bufp->fullIData(oldp+236,(vlSelf->top__DOT__pipeline_DE__DOT__RD2E),32);
    bufp->fullIData(oldp+237,(vlSelf->top__DOT__pipeline_DE__DOT__PCD),32);
    bufp->fullIData(oldp+238,(vlSelf->top__DOT__pipeline_DE__DOT__PCE),32);
    bufp->fullCData(oldp+239,(vlSelf->top__DOT__pipeline_DE__DOT__Rs1D),5);
    bufp->fullCData(oldp+240,(vlSelf->top__DOT__pipeline_DE__DOT__Rs1E),5);
    bufp->fullCData(oldp+241,(vlSelf->top__DOT__pipeline_DE__DOT__Rs2D),5);
    bufp->fullCData(oldp+242,(vlSelf->top__DOT__pipeline_DE__DOT__Rs2E),5);
    bufp->fullCData(oldp+243,(vlSelf->top__DOT__pipeline_DE__DOT__RdD),5);
    bufp->fullCData(oldp+244,(vlSelf->top__DOT__pipeline_DE__DOT__RdE),5);
    bufp->fullIData(oldp+245,(vlSelf->top__DOT__pipeline_DE__DOT__ExtImmD),32);
    bufp->fullIData(oldp+246,(vlSelf->top__DOT__pipeline_DE__DOT__ExtImmE),32);
    bufp->fullIData(oldp+247,(vlSelf->top__DOT__pipeline_DE__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+248,(vlSelf->top__DOT__pipeline_DE__DOT__PCPlus4E),32);
    bufp->fullCData(oldp+249,(vlSelf->top__DOT__pipeline_DE__DOT__modeAddrD),3);
    bufp->fullCData(oldp+250,(vlSelf->top__DOT__pipeline_DE__DOT__modeAddrE),3);
    bufp->fullBit(oldp+251,(vlSelf->top__DOT__pipeline_EM__DOT__clk));
    bufp->fullBit(oldp+252,(vlSelf->top__DOT__pipeline_EM__DOT__RegWriteE));
    bufp->fullBit(oldp+253,(vlSelf->top__DOT__pipeline_EM__DOT__RegWriteM));
    bufp->fullCData(oldp+254,(vlSelf->top__DOT__pipeline_EM__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+255,(vlSelf->top__DOT__pipeline_EM__DOT__ResultSrcM),2);
    bufp->fullBit(oldp+256,(vlSelf->top__DOT__pipeline_EM__DOT__MemWriteE));
    bufp->fullBit(oldp+257,(vlSelf->top__DOT__pipeline_EM__DOT__MemWriteM));
    bufp->fullIData(oldp+258,(vlSelf->top__DOT__pipeline_EM__DOT__ALUResultE),32);
    bufp->fullIData(oldp+259,(vlSelf->top__DOT__pipeline_EM__DOT__ALUResultM),32);
    bufp->fullIData(oldp+260,(vlSelf->top__DOT__pipeline_EM__DOT__WriteDataE),32);
    bufp->fullIData(oldp+261,(vlSelf->top__DOT__pipeline_EM__DOT__WriteDataM),32);
    bufp->fullCData(oldp+262,(vlSelf->top__DOT__pipeline_EM__DOT__RdE),5);
    bufp->fullCData(oldp+263,(vlSelf->top__DOT__pipeline_EM__DOT__RdM),5);
    bufp->fullIData(oldp+264,(vlSelf->top__DOT__pipeline_EM__DOT__PCPlus4E),32);
    bufp->fullIData(oldp+265,(vlSelf->top__DOT__pipeline_EM__DOT__PCPlus4M),32);
    bufp->fullCData(oldp+266,(vlSelf->top__DOT__pipeline_EM__DOT__modeAddrE),3);
    bufp->fullCData(oldp+267,(vlSelf->top__DOT__pipeline_EM__DOT__modeAddrM),3);
    bufp->fullBit(oldp+268,(vlSelf->top__DOT__pipeline_FD__DOT__clk));
    bufp->fullBit(oldp+269,(vlSelf->top__DOT__pipeline_FD__DOT__flush));
    bufp->fullBit(oldp+270,(vlSelf->top__DOT__pipeline_FD__DOT__stall));
    bufp->fullIData(oldp+271,(vlSelf->top__DOT__pipeline_FD__DOT__RD),32);
    bufp->fullIData(oldp+272,(vlSelf->top__DOT__pipeline_FD__DOT__InstrD),32);
    bufp->fullIData(oldp+273,(vlSelf->top__DOT__pipeline_FD__DOT__PCF),32);
    bufp->fullIData(oldp+274,(vlSelf->top__DOT__pipeline_FD__DOT__PCD),32);
    bufp->fullIData(oldp+275,(vlSelf->top__DOT__pipeline_FD__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+276,(vlSelf->top__DOT__pipeline_FD__DOT__PCPlus4D),32);
    bufp->fullBit(oldp+277,(vlSelf->top__DOT__pipeline_MW__DOT__clk));
    bufp->fullBit(oldp+278,(vlSelf->top__DOT__pipeline_MW__DOT__RegWriteM));
    bufp->fullBit(oldp+279,(vlSelf->top__DOT__pipeline_MW__DOT__RegWriteW));
    bufp->fullCData(oldp+280,(vlSelf->top__DOT__pipeline_MW__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+281,(vlSelf->top__DOT__pipeline_MW__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+282,(vlSelf->top__DOT__pipeline_MW__DOT__ALUResultM),32);
    bufp->fullIData(oldp+283,(vlSelf->top__DOT__pipeline_MW__DOT__ALUResultW),32);
    bufp->fullIData(oldp+284,(vlSelf->top__DOT__pipeline_MW__DOT__RD),32);
    bufp->fullIData(oldp+285,(vlSelf->top__DOT__pipeline_MW__DOT__ReadDataW),32);
    bufp->fullCData(oldp+286,(vlSelf->top__DOT__pipeline_MW__DOT__RdM),5);
    bufp->fullCData(oldp+287,(vlSelf->top__DOT__pipeline_MW__DOT__RdW),5);
    bufp->fullIData(oldp+288,(vlSelf->top__DOT__pipeline_MW__DOT__PCPlus4M),32);
    bufp->fullIData(oldp+289,(vlSelf->top__DOT__pipeline_MW__DOT__PCPlus4W),32);
    bufp->fullBit(oldp+290,(vlSelf->top__DOT__program_counter__DOT__clk));
    bufp->fullBit(oldp+291,(vlSelf->top__DOT__program_counter__DOT__rst));
    bufp->fullIData(oldp+292,(vlSelf->top__DOT__program_counter__DOT__PC),32);
    bufp->fullBit(oldp+293,(vlSelf->top__DOT__program_counter__DOT__stall));
    bufp->fullIData(oldp+294,(vlSelf->top__DOT__program_counter__DOT__PCF),32);
    bufp->fullBit(oldp+295,(vlSelf->top__DOT__regfile__DOT__clk));
    bufp->fullCData(oldp+296,(vlSelf->top__DOT__regfile__DOT__AD1),5);
    bufp->fullCData(oldp+297,(vlSelf->top__DOT__regfile__DOT__AD2),5);
    bufp->fullCData(oldp+298,(vlSelf->top__DOT__regfile__DOT__AD3),5);
    bufp->fullBit(oldp+299,(vlSelf->top__DOT__regfile__DOT__WE3));
    bufp->fullIData(oldp+300,(vlSelf->top__DOT__regfile__DOT__WD3),32);
    bufp->fullIData(oldp+301,(vlSelf->top__DOT__regfile__DOT__RD1),32);
    bufp->fullIData(oldp+302,(vlSelf->top__DOT__regfile__DOT__RD2),32);
    bufp->fullIData(oldp+303,(vlSelf->top__DOT__regfile__DOT__a0),32);
    bufp->fullIData(oldp+304,(vlSelf->top__DOT__regfile__DOT__a1),32);
    bufp->fullIData(oldp+305,(vlSelf->top__DOT__regfile__DOT__a2),32);
    bufp->fullIData(oldp+306,(vlSelf->top__DOT__regfile__DOT__a3),32);
    bufp->fullIData(oldp+307,(vlSelf->top__DOT__regfile__DOT__a4),32);
    bufp->fullIData(oldp+308,(vlSelf->top__DOT__regfile__DOT__a5),32);
    bufp->fullIData(oldp+309,(vlSelf->top__DOT__regfile__DOT__a6),32);
    bufp->fullIData(oldp+310,(vlSelf->top__DOT__regfile__DOT__a7),32);
    bufp->fullIData(oldp+311,(vlSelf->top__DOT__regfile__DOT__t0),32);
    bufp->fullIData(oldp+312,(vlSelf->top__DOT__regfile__DOT__t1),32);
    bufp->fullIData(oldp+313,(vlSelf->top__DOT__regfile__DOT__t2),32);
    bufp->fullIData(oldp+314,(vlSelf->top__DOT__regfile__DOT__t3),32);
    bufp->fullIData(oldp+315,(vlSelf->top__DOT__regfile__DOT__t4),32);
    bufp->fullIData(oldp+316,(vlSelf->top__DOT__regfile__DOT__t5),32);
    bufp->fullIData(oldp+317,(vlSelf->top__DOT__regfile__DOT__t6),32);
    bufp->fullIData(oldp+318,(vlSelf->top__DOT__regfile__DOT__s0),32);
    bufp->fullIData(oldp+319,(vlSelf->top__DOT__regfile__DOT__s1),32);
    bufp->fullIData(oldp+320,(vlSelf->top__DOT__regfile__DOT__s2),32);
    bufp->fullIData(oldp+321,(vlSelf->top__DOT__regfile__DOT__s3),32);
    bufp->fullIData(oldp+322,(vlSelf->top__DOT__regfile__DOT__s4),32);
    bufp->fullIData(oldp+323,(vlSelf->top__DOT__regfile__DOT__s5),32);
    bufp->fullIData(oldp+324,(vlSelf->top__DOT__regfile__DOT__s6),32);
    bufp->fullIData(oldp+325,(vlSelf->top__DOT__regfile__DOT__s7),32);
    bufp->fullIData(oldp+326,(vlSelf->top__DOT__regfile__DOT__s8),32);
    bufp->fullIData(oldp+327,(vlSelf->top__DOT__regfile__DOT__s9),32);
    bufp->fullIData(oldp+328,(vlSelf->top__DOT__regfile__DOT__s10),32);
    bufp->fullIData(oldp+329,(vlSelf->top__DOT__regfile__DOT__s11),32);
    bufp->fullIData(oldp+330,(vlSelf->top__DOT__regfile__DOT__registerfile_array[0]),32);
    bufp->fullIData(oldp+331,(vlSelf->top__DOT__regfile__DOT__registerfile_array[1]),32);
    bufp->fullIData(oldp+332,(vlSelf->top__DOT__regfile__DOT__registerfile_array[2]),32);
    bufp->fullIData(oldp+333,(vlSelf->top__DOT__regfile__DOT__registerfile_array[3]),32);
    bufp->fullIData(oldp+334,(vlSelf->top__DOT__regfile__DOT__registerfile_array[4]),32);
    bufp->fullIData(oldp+335,(vlSelf->top__DOT__regfile__DOT__registerfile_array[5]),32);
    bufp->fullIData(oldp+336,(vlSelf->top__DOT__regfile__DOT__registerfile_array[6]),32);
    bufp->fullIData(oldp+337,(vlSelf->top__DOT__regfile__DOT__registerfile_array[7]),32);
    bufp->fullIData(oldp+338,(vlSelf->top__DOT__regfile__DOT__registerfile_array[8]),32);
    bufp->fullIData(oldp+339,(vlSelf->top__DOT__regfile__DOT__registerfile_array[9]),32);
    bufp->fullIData(oldp+340,(vlSelf->top__DOT__regfile__DOT__registerfile_array[10]),32);
    bufp->fullIData(oldp+341,(vlSelf->top__DOT__regfile__DOT__registerfile_array[11]),32);
    bufp->fullIData(oldp+342,(vlSelf->top__DOT__regfile__DOT__registerfile_array[12]),32);
    bufp->fullIData(oldp+343,(vlSelf->top__DOT__regfile__DOT__registerfile_array[13]),32);
    bufp->fullIData(oldp+344,(vlSelf->top__DOT__regfile__DOT__registerfile_array[14]),32);
    bufp->fullIData(oldp+345,(vlSelf->top__DOT__regfile__DOT__registerfile_array[15]),32);
    bufp->fullIData(oldp+346,(vlSelf->top__DOT__regfile__DOT__registerfile_array[16]),32);
    bufp->fullIData(oldp+347,(vlSelf->top__DOT__regfile__DOT__registerfile_array[17]),32);
    bufp->fullIData(oldp+348,(vlSelf->top__DOT__regfile__DOT__registerfile_array[18]),32);
    bufp->fullIData(oldp+349,(vlSelf->top__DOT__regfile__DOT__registerfile_array[19]),32);
    bufp->fullIData(oldp+350,(vlSelf->top__DOT__regfile__DOT__registerfile_array[20]),32);
    bufp->fullIData(oldp+351,(vlSelf->top__DOT__regfile__DOT__registerfile_array[21]),32);
    bufp->fullIData(oldp+352,(vlSelf->top__DOT__regfile__DOT__registerfile_array[22]),32);
    bufp->fullIData(oldp+353,(vlSelf->top__DOT__regfile__DOT__registerfile_array[23]),32);
    bufp->fullIData(oldp+354,(vlSelf->top__DOT__regfile__DOT__registerfile_array[24]),32);
    bufp->fullIData(oldp+355,(vlSelf->top__DOT__regfile__DOT__registerfile_array[25]),32);
    bufp->fullIData(oldp+356,(vlSelf->top__DOT__regfile__DOT__registerfile_array[26]),32);
    bufp->fullIData(oldp+357,(vlSelf->top__DOT__regfile__DOT__registerfile_array[27]),32);
    bufp->fullIData(oldp+358,(vlSelf->top__DOT__regfile__DOT__registerfile_array[28]),32);
    bufp->fullIData(oldp+359,(vlSelf->top__DOT__regfile__DOT__registerfile_array[29]),32);
    bufp->fullIData(oldp+360,(vlSelf->top__DOT__regfile__DOT__registerfile_array[30]),32);
    bufp->fullIData(oldp+361,(vlSelf->top__DOT__regfile__DOT__registerfile_array[31]),32);
    bufp->fullCData(oldp+362,(vlSelf->top__DOT__regfile_mux__DOT__sel),2);
    bufp->fullIData(oldp+363,(vlSelf->top__DOT__regfile_mux__DOT__in0),32);
    bufp->fullIData(oldp+364,(vlSelf->top__DOT__regfile_mux__DOT__in1),32);
    bufp->fullIData(oldp+365,(vlSelf->top__DOT__regfile_mux__DOT__in2),32);
    bufp->fullIData(oldp+366,(vlSelf->top__DOT__regfile_mux__DOT__out),32);
    bufp->fullCData(oldp+367,(vlSelf->top__DOT__sign_extend__DOT__ImmSrc),3);
    bufp->fullIData(oldp+368,(vlSelf->top__DOT__sign_extend__DOT__ImmInput),32);
    bufp->fullIData(oldp+369,(vlSelf->top__DOT__sign_extend__DOT__ImmExt),32);
    bufp->fullIData(oldp+370,(0x20U),32);
    bufp->fullBit(oldp+371,(vlSelf->top__DOT__ALUResult));
    bufp->fullBit(oldp+372,(vlSelf->top__DOT__ImmSrcD));
    bufp->fullBit(oldp+373,(vlSelf->top__DOT__modeAddrD));
    bufp->fullIData(oldp+374,(4U),32);
    bufp->fullIData(oldp+375,(5U),32);
    bufp->fullIData(oldp+376,(0x1fU),32);
    bufp->fullIData(oldp+377,(0xbU),32);
    bufp->fullIData(oldp+378,(0x100U),32);
}
