// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"
#include "Vtop___024unit.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{
}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
    , TOP____024unit{this, Verilated::catName(namep, "$unit")}
{
        // Check resources
        Verilated::stackCheck(281);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-12);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT____024unit = &TOP____024unit;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP____024unit.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope___024unit.configure(this, name(), "$unit", "$unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top.configure(this, name(), "top", "top", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__BPU_mux.configure(this, name(), "top.BPU_mux", "BPU_mux", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__PC_mux.configure(this, name(), "top.PC_mux", "PC_mux", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__alu.configure(this, name(), "top.alu", "alu", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__branch_prediction_unit.configure(this, name(), "top.branch_prediction_unit", "branch_prediction_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__cached_data_memory.configure(this, name(), "top.cached_data_memory", "cached_data_memory", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__cached_data_memory__cache.configure(this, name(), "top.cached_data_memory.cache", "cache", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__control_unit.configure(this, name(), "top.control_unit", "control_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__control_unit__alu_decoder.configure(this, name(), "top.control_unit.alu_decoder", "alu_decoder", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__forwardAE_mux.configure(this, name(), "top.forwardAE_mux", "forwardAE_mux", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__forwardBE_mux.configure(this, name(), "top.forwardBE_mux", "forwardBE_mux", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__hazard_unit.configure(this, name(), "top.hazard_unit", "hazard_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__instruction_memory.configure(this, name(), "top.instruction_memory", "instruction_memory", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__pipeline_DE.configure(this, name(), "top.pipeline_DE", "pipeline_DE", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__pipeline_EM.configure(this, name(), "top.pipeline_EM", "pipeline_EM", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__pipeline_FD.configure(this, name(), "top.pipeline_FD", "pipeline_FD", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__pipeline_MW.configure(this, name(), "top.pipeline_MW", "pipeline_MW", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__program_counter.configure(this, name(), "top.program_counter", "program_counter", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__regfile.configure(this, name(), "top.regfile", "regfile", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__regfile_mux.configure(this, name(), "top.regfile_mux", "regfile_mux", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__sign_extend.configure(this, name(), "top.sign_extend", "sign_extend", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"a0", &(TOP.a0), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a1", &(TOP.a1), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a2", &(TOP.a2), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a3", &(TOP.a3), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a4", &(TOP.a4), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a5", &(TOP.a5), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a6", &(TOP.a6), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"a7", &(TOP.a7), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOP.rst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"s0", &(TOP.s0), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s1", &(TOP.s1), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s10", &(TOP.s10), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s11", &(TOP.s11), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s2", &(TOP.s2), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s3", &(TOP.s3), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s4", &(TOP.s4), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s5", &(TOP.s5), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s6", &(TOP.s6), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s7", &(TOP.s7), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s8", &(TOP.s8), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"s9", &(TOP.s9), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t0", &(TOP.t0), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t1", &(TOP.t1), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t2", &(TOP.t2), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t3", &(TOP.t3), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t4", &(TOP.t4), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t5", &(TOP.t5), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"t6", &(TOP.t6), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"trigger", &(TOP.trigger), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope___024unit.varInsert(__Vfinal,"SETS", const_cast<void*>(static_cast<const void*>(&(TOP____024unit.SETS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope___024unit.varInsert(__Vfinal,"TAG_LSB", const_cast<void*>(static_cast<const void*>(&(TOP____024unit.TAG_LSB))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope___024unit.varInsert(__Vfinal,"TAG_MSB", const_cast<void*>(static_cast<const void*>(&(TOP____024unit.TAG_MSB))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ALUControlD", &(TOP.top__DOT__ALUControlD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top.varInsert(__Vfinal,"ALUControlE", &(TOP.top__DOT__ALUControlE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top.varInsert(__Vfinal,"ALUResultE", &(TOP.top__DOT__ALUResultE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ALUResultM", &(TOP.top__DOT__ALUResultM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ALUResultW", &(TOP.top__DOT__ALUResultW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ALUSrcD", &(TOP.top__DOT__ALUSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"ALUSrcE", &(TOP.top__DOT__ALUSrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"BPU_Src", &(TOP.top__DOT__BPU_Src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"BranchD", &(TOP.top__DOT__BranchD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"BranchE", &(TOP.top__DOT__BranchE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"ExtImmD", &(TOP.top__DOT__ExtImmD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ExtImmE", &(TOP.top__DOT__ExtImmE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ForwardAE", &(TOP.top__DOT__ForwardAE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ForwardBE", &(TOP.top__DOT__ForwardBE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ImmSrc", &(TOP.top__DOT__ImmSrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top.varInsert(__Vfinal,"InstrD", &(TOP.top__DOT__InstrD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"InstrE", &(TOP.top__DOT__InstrE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"InstrF", &(TOP.top__DOT__InstrF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"InstrM", &(TOP.top__DOT__InstrM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"InstrW", &(TOP.top__DOT__InstrW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"JALRD", &(TOP.top__DOT__JALRD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"JALRE", &(TOP.top__DOT__JALRE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"JumpD", &(TOP.top__DOT__JumpD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"JumpE", &(TOP.top__DOT__JumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemReadD", &(TOP.top__DOT__MemReadD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemReadE", &(TOP.top__DOT__MemReadE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemReadM", &(TOP.top__DOT__MemReadM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemWriteD", &(TOP.top__DOT__MemWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemWriteE", &(TOP.top__DOT__MemWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"MemWriteM", &(TOP.top__DOT__MemWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"PC", &(TOP.top__DOT__PC), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCD", &(TOP.top__DOT__PCD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCE", &(TOP.top__DOT__PCE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCF", &(TOP.top__DOT__PCF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCPlus4D", &(TOP.top__DOT__PCPlus4D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCPlus4E", &(TOP.top__DOT__PCPlus4E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCPlus4F", &(TOP.top__DOT__PCPlus4F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCPlus4M", &(TOP.top__DOT__PCPlus4M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PCPlus4W", &(TOP.top__DOT__PCPlus4W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PC_next", &(TOP.top__DOT__PC_next), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"PC_predict", &(TOP.top__DOT__PC_predict), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RD", &(TOP.top__DOT__RD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RD1", &(TOP.top__DOT__RD1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RD1E", &(TOP.top__DOT__RD1E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RD2", &(TOP.top__DOT__RD2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RD2E", &(TOP.top__DOT__RD2E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RdD", &(TOP.top__DOT__RdD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"RdE", &(TOP.top__DOT__RdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"RdM", &(TOP.top__DOT__RdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"RdW", &(TOP.top__DOT__RdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"ReadDataM", &(TOP.top__DOT__ReadDataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"ReadDataW", &(TOP.top__DOT__ReadDataW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"RegWriteD", &(TOP.top__DOT__RegWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"RegWriteE", &(TOP.top__DOT__RegWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"RegWriteM", &(TOP.top__DOT__RegWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"RegWriteW", &(TOP.top__DOT__RegWriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"ResultSrcD", &(TOP.top__DOT__ResultSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ResultSrcE", &(TOP.top__DOT__ResultSrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ResultSrcM", &(TOP.top__DOT__ResultSrcM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ResultSrcW", &(TOP.top__DOT__ResultSrcW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top.varInsert(__Vfinal,"ResultW", &(TOP.top__DOT__ResultW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"Rs1D", &(TOP.top__DOT__Rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"Rs1E", &(TOP.top__DOT__Rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"Rs2D", &(TOP.top__DOT__Rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"Rs2E", &(TOP.top__DOT__Rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top.varInsert(__Vfinal,"SrcAE", &(TOP.top__DOT__SrcAE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"WriteDataE", &(TOP.top__DOT__WriteDataE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"WriteDataM", &(TOP.top__DOT__WriteDataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"Zero", &(TOP.top__DOT__Zero), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"a0", &(TOP.top__DOT__a0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a1", &(TOP.top__DOT__a1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a2", &(TOP.top__DOT__a2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a3", &(TOP.top__DOT__a3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a4", &(TOP.top__DOT__a4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a5", &(TOP.top__DOT__a5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a6", &(TOP.top__DOT__a6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"a7", &(TOP.top__DOT__a7), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"clk", &(TOP.top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"flush", &(TOP.top__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"flushBranch", &(TOP.top__DOT__flushBranch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"flushDE", &(TOP.top__DOT__flushDE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"miss_stall", &(TOP.top__DOT__miss_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"modeAddrD", &(TOP.top__DOT__modeAddrD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top.varInsert(__Vfinal,"modeAddrE", &(TOP.top__DOT__modeAddrE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top.varInsert(__Vfinal,"modeAddrM", &(TOP.top__DOT__modeAddrM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top.varInsert(__Vfinal,"rst", &(TOP.top__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"s0", &(TOP.top__DOT__s0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s1", &(TOP.top__DOT__s1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s10", &(TOP.top__DOT__s10), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s11", &(TOP.top__DOT__s11), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s2", &(TOP.top__DOT__s2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s3", &(TOP.top__DOT__s3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s4", &(TOP.top__DOT__s4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s5", &(TOP.top__DOT__s5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s6", &(TOP.top__DOT__s6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s7", &(TOP.top__DOT__s7), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s8", &(TOP.top__DOT__s8), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"s9", &(TOP.top__DOT__s9), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"stall", &(TOP.top__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"t0", &(TOP.top__DOT__t0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t1", &(TOP.top__DOT__t1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t2", &(TOP.top__DOT__t2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t3", &(TOP.top__DOT__t3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t4", &(TOP.top__DOT__t4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t5", &(TOP.top__DOT__t5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"t6", &(TOP.top__DOT__t6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"trigger", &(TOP.top__DOT__trigger), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__BPU_mux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__BPU_mux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__BPU_mux.varInsert(__Vfinal,"in0", &(TOP.top__DOT__BPU_mux__DOT__in0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__BPU_mux.varInsert(__Vfinal,"in1", &(TOP.top__DOT__BPU_mux__DOT__in1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__BPU_mux.varInsert(__Vfinal,"out", &(TOP.top__DOT__BPU_mux__DOT__out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__BPU_mux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__BPU_mux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"ALUResult", &(TOP.top__DOT__PC_mux__DOT__ALUResult), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"BranchE", &(TOP.top__DOT__PC_mux__DOT__BranchE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"JALRE", &(TOP.top__DOT__PC_mux__DOT__JALRE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"JumpE", &(TOP.top__DOT__PC_mux__DOT__JumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"PC", &(TOP.top__DOT__PC_mux__DOT__PC), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"PCPlus4F", &(TOP.top__DOT__PC_mux__DOT__PCPlus4F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"PCTarget", &(TOP.top__DOT__PC_mux__DOT__PCTarget), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__PC_mux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__PC_mux.varInsert(__Vfinal,"ZeroE", &(TOP.top__DOT__PC_mux__DOT__ZeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__alu.varInsert(__Vfinal,"ALUResult", &(TOP.top__DOT__alu__DOT__ALUResult), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__alu.varInsert(__Vfinal,"ALUctrl", &(TOP.top__DOT__alu__DOT__ALUctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__alu.varInsert(__Vfinal,"CONTROL_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__alu__DOT__CONTROL_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__alu.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__alu__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__alu.varInsert(__Vfinal,"SrcA", &(TOP.top__DOT__alu__DOT__SrcA), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__alu.varInsert(__Vfinal,"SrcB", &(TOP.top__DOT__alu__DOT__SrcB), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__alu.varInsert(__Vfinal,"ZeroE", &(TOP.top__DOT__alu__DOT__ZeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"BranchE", &(TOP.top__DOT__branch_prediction_unit__DOT__BranchE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__branch_prediction_unit__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"JumpE", &(TOP.top__DOT__branch_prediction_unit__DOT__JumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"PCBPU", &(TOP.top__DOT__branch_prediction_unit__DOT__PCBPU), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"PCBPUSrc", &(TOP.top__DOT__branch_prediction_unit__DOT__PCBPUSrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"PCF", &(TOP.top__DOT__branch_prediction_unit__DOT__PCF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"RD", &(TOP.top__DOT__branch_prediction_unit__DOT__RD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"ZeroE", &(TOP.top__DOT__branch_prediction_unit__DOT__ZeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"backwardJumpCounter", &(TOP.top__DOT__branch_prediction_unit__DOT__backwardJumpCounter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"backwardJumpDecisionCorrect", &(TOP.top__DOT__branch_prediction_unit__DOT__backwardJumpDecisionCorrect), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"branch_queue", &(TOP.top__DOT__branch_prediction_unit__DOT__branch_queue), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"clk", &(TOP.top__DOT__branch_prediction_unit__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"flushBranch", &(TOP.top__DOT__branch_prediction_unit__DOT__flushBranch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"forwardJumpCounter", &(TOP.top__DOT__branch_prediction_unit__DOT__forwardJumpCounter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"forwardJumpDecisionCorrect", &(TOP.top__DOT__branch_prediction_unit__DOT__forwardJumpDecisionCorrect), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"newBranch", &(TOP.top__DOT__branch_prediction_unit__DOT__newBranch), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,65,0);
        __Vscope_top__branch_prediction_unit.varInsert(__Vfinal,"oldBranch", &(TOP.top__DOT__branch_prediction_unit__DOT__oldBranch), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,65,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__cached_data_memory__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__cached_data_memory__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"RE", &(TOP.top__DOT__cached_data_memory__DOT__RE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"WE", &(TOP.top__DOT__cached_data_memory__DOT__WE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"addr", &(TOP.top__DOT__cached_data_memory__DOT__addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"byte0", &(TOP.top__DOT__cached_data_memory__DOT__byte0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"byte1", &(TOP.top__DOT__cached_data_memory__DOT__byte1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"byte2", &(TOP.top__DOT__cached_data_memory__DOT__byte2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"byte3", &(TOP.top__DOT__cached_data_memory__DOT__byte3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"clk", &(TOP.top__DOT__cached_data_memory__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"data_out", &(TOP.top__DOT__cached_data_memory__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"miss_stall", &(TOP.top__DOT__cached_data_memory__DOT__miss_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"modeAddr", &(TOP.top__DOT__cached_data_memory__DOT__modeAddr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"out_cache", &(TOP.top__DOT__cached_data_memory__DOT__out_cache), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"rst", &(TOP.top__DOT__cached_data_memory__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory.varInsert(__Vfinal,"write_data", &(TOP.top__DOT__cached_data_memory__DOT__write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"RE", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__RE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"WE", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__WE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"addr", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"block", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__block), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"cache_line", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__cache_line), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,86,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"cache_line_data", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__cache_line_data), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"cache_line_valid", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__cache_line_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"cache_mem", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__cache_mem), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,86,0 ,0,255);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"cache_out", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__cache_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"clk", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"current_state", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__current_state), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"miss_stall", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__miss_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"modeAddr", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__modeAddr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"next_state", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__next_state), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"ram_array", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__ram_array), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,2 ,7,0 ,131071,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"rst", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"set", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__set), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_top__cached_data_memory__cache.varInsert(__Vfinal,"write_data", &(TOP.top__DOT__cached_data_memory__DOT__cache__DOT__write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"ALUControlD", &(TOP.top__DOT__control_unit__DOT__ALUControlD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"ALUOp", &(TOP.top__DOT__control_unit__DOT__ALUOp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"ALUSrcD", &(TOP.top__DOT__control_unit__DOT__ALUSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"BranchD", &(TOP.top__DOT__control_unit__DOT__BranchD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__control_unit__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"ImmSrcD", &(TOP.top__DOT__control_unit__DOT__ImmSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"InstrD", &(TOP.top__DOT__control_unit__DOT__InstrD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"JALRD", &(TOP.top__DOT__control_unit__DOT__JALRD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"JumpD", &(TOP.top__DOT__control_unit__DOT__JumpD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"Load", &(TOP.top__DOT__control_unit__DOT__Load), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"MemReadD", &(TOP.top__DOT__control_unit__DOT__MemReadD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"MemWriteD", &(TOP.top__DOT__control_unit__DOT__MemWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"RegWriteD", &(TOP.top__DOT__control_unit__DOT__RegWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"ResultSrcD", &(TOP.top__DOT__control_unit__DOT__ResultSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"Store", &(TOP.top__DOT__control_unit__DOT__Store), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__control_unit__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,14,12);
        __Vscope_top__control_unit.varInsert(__Vfinal,"funct7", &(TOP.top__DOT__control_unit__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"modeAddr", &(TOP.top__DOT__control_unit__DOT__modeAddr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__control_unit.varInsert(__Vfinal,"op", &(TOP.top__DOT__control_unit__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__control_unit__alu_decoder.varInsert(__Vfinal,"ALUControl", &(TOP.top__DOT__control_unit__DOT__alu_decoder__DOT__ALUControl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__control_unit__alu_decoder.varInsert(__Vfinal,"ALUOp", &(TOP.top__DOT__control_unit__DOT__alu_decoder__DOT__ALUOp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__control_unit__alu_decoder.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__control_unit__DOT__alu_decoder__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__control_unit__alu_decoder.varInsert(__Vfinal,"funct7", &(TOP.top__DOT__control_unit__DOT__alu_decoder__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__control_unit__alu_decoder.varInsert(__Vfinal,"op", &(TOP.top__DOT__control_unit__DOT__alu_decoder__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__forwardAE_mux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"in0", &(TOP.top__DOT__forwardAE_mux__DOT__in0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"in1", &(TOP.top__DOT__forwardAE_mux__DOT__in1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"in2", &(TOP.top__DOT__forwardAE_mux__DOT__in2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"in3", &(TOP.top__DOT__forwardAE_mux__DOT__in3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"out", &(TOP.top__DOT__forwardAE_mux__DOT__out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardAE_mux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__forwardAE_mux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__forwardBE_mux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"in0", &(TOP.top__DOT__forwardBE_mux__DOT__in0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"in1", &(TOP.top__DOT__forwardBE_mux__DOT__in1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"in2", &(TOP.top__DOT__forwardBE_mux__DOT__in2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"in3", &(TOP.top__DOT__forwardBE_mux__DOT__in3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"out", &(TOP.top__DOT__forwardBE_mux__DOT__out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__forwardBE_mux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__forwardBE_mux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"ForwardAE", &(TOP.top__DOT__hazard_unit__DOT__ForwardAE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"ForwardBE", &(TOP.top__DOT__hazard_unit__DOT__ForwardBE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"JumpE", &(TOP.top__DOT__hazard_unit__DOT__JumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"MemReadE", &(TOP.top__DOT__hazard_unit__DOT__MemReadE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"MemReadM", &(TOP.top__DOT__hazard_unit__DOT__MemReadM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"RdE", &(TOP.top__DOT__hazard_unit__DOT__RdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"RdM", &(TOP.top__DOT__hazard_unit__DOT__RdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"RdW", &(TOP.top__DOT__hazard_unit__DOT__RdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"RegWriteM", &(TOP.top__DOT__hazard_unit__DOT__RegWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"RegWriteW", &(TOP.top__DOT__hazard_unit__DOT__RegWriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"Rs1D", &(TOP.top__DOT__hazard_unit__DOT__Rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"Rs1E", &(TOP.top__DOT__hazard_unit__DOT__Rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"Rs2D", &(TOP.top__DOT__hazard_unit__DOT__Rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"Rs2E", &(TOP.top__DOT__hazard_unit__DOT__Rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__hazard_unit__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"flush", &(TOP.top__DOT__hazard_unit__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"flushBranch", &(TOP.top__DOT__hazard_unit__DOT__flushBranch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"flushDE", &(TOP.top__DOT__hazard_unit__DOT__flushDE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"miss_stall", &(TOP.top__DOT__hazard_unit__DOT__miss_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__hazard_unit.varInsert(__Vfinal,"stall", &(TOP.top__DOT__hazard_unit__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__instruction_memory.varInsert(__Vfinal,"PC", &(TOP.top__DOT__instruction_memory__DOT__PC), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__instruction_memory.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__instruction_memory__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__instruction_memory.varInsert(__Vfinal,"instr", &(TOP.top__DOT__instruction_memory__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__instruction_memory.varInsert(__Vfinal,"rom_array", &(TOP.top__DOT__instruction_memory__DOT__rom_array), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,2 ,7,0 ,65535,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ALUControlD", &(TOP.top__DOT__pipeline_DE__DOT__ALUControlD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ALUControlE", &(TOP.top__DOT__pipeline_DE__DOT__ALUControlE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ALUSrcD", &(TOP.top__DOT__pipeline_DE__DOT__ALUSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ALUSrcE", &(TOP.top__DOT__pipeline_DE__DOT__ALUSrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"BranchD", &(TOP.top__DOT__pipeline_DE__DOT__BranchD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"BranchE", &(TOP.top__DOT__pipeline_DE__DOT__BranchE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_DE__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ExtImmD", &(TOP.top__DOT__pipeline_DE__DOT__ExtImmD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ExtImmE", &(TOP.top__DOT__pipeline_DE__DOT__ExtImmE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"InstrD", &(TOP.top__DOT__pipeline_DE__DOT__InstrD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"InstrE", &(TOP.top__DOT__pipeline_DE__DOT__InstrE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"JALRD", &(TOP.top__DOT__pipeline_DE__DOT__JALRD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"JALRE", &(TOP.top__DOT__pipeline_DE__DOT__JALRE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"JumpD", &(TOP.top__DOT__pipeline_DE__DOT__JumpD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"JumpE", &(TOP.top__DOT__pipeline_DE__DOT__JumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"MemReadD", &(TOP.top__DOT__pipeline_DE__DOT__MemReadD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"MemReadE", &(TOP.top__DOT__pipeline_DE__DOT__MemReadE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"MemWriteD", &(TOP.top__DOT__pipeline_DE__DOT__MemWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"MemWriteE", &(TOP.top__DOT__pipeline_DE__DOT__MemWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"PCD", &(TOP.top__DOT__pipeline_DE__DOT__PCD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"PCE", &(TOP.top__DOT__pipeline_DE__DOT__PCE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"PCPlus4D", &(TOP.top__DOT__pipeline_DE__DOT__PCPlus4D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"PCPlus4E", &(TOP.top__DOT__pipeline_DE__DOT__PCPlus4E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RD1", &(TOP.top__DOT__pipeline_DE__DOT__RD1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RD1E", &(TOP.top__DOT__pipeline_DE__DOT__RD1E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RD2", &(TOP.top__DOT__pipeline_DE__DOT__RD2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RD2E", &(TOP.top__DOT__pipeline_DE__DOT__RD2E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RdD", &(TOP.top__DOT__pipeline_DE__DOT__RdD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RdE", &(TOP.top__DOT__pipeline_DE__DOT__RdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RegWriteD", &(TOP.top__DOT__pipeline_DE__DOT__RegWriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"RegWriteE", &(TOP.top__DOT__pipeline_DE__DOT__RegWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ResultSrcD", &(TOP.top__DOT__pipeline_DE__DOT__ResultSrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"ResultSrcE", &(TOP.top__DOT__pipeline_DE__DOT__ResultSrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"Rs1D", &(TOP.top__DOT__pipeline_DE__DOT__Rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"Rs1E", &(TOP.top__DOT__pipeline_DE__DOT__Rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"Rs2D", &(TOP.top__DOT__pipeline_DE__DOT__Rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"Rs2E", &(TOP.top__DOT__pipeline_DE__DOT__Rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_DE__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"clk", &(TOP.top__DOT__pipeline_DE__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"flushBranch", &(TOP.top__DOT__pipeline_DE__DOT__flushBranch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"modeAddrD", &(TOP.top__DOT__pipeline_DE__DOT__modeAddrD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__pipeline_DE.varInsert(__Vfinal,"modeAddrE", &(TOP.top__DOT__pipeline_DE__DOT__modeAddrE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"ALUResultE", &(TOP.top__DOT__pipeline_EM__DOT__ALUResultE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"ALUResultM", &(TOP.top__DOT__pipeline_EM__DOT__ALUResultM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_EM__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"InstrE", &(TOP.top__DOT__pipeline_EM__DOT__InstrE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"InstrM", &(TOP.top__DOT__pipeline_EM__DOT__InstrM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"MemReadE", &(TOP.top__DOT__pipeline_EM__DOT__MemReadE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"MemReadM", &(TOP.top__DOT__pipeline_EM__DOT__MemReadM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"MemWriteE", &(TOP.top__DOT__pipeline_EM__DOT__MemWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"MemWriteM", &(TOP.top__DOT__pipeline_EM__DOT__MemWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"PCPlus4E", &(TOP.top__DOT__pipeline_EM__DOT__PCPlus4E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"PCPlus4M", &(TOP.top__DOT__pipeline_EM__DOT__PCPlus4M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"RdE", &(TOP.top__DOT__pipeline_EM__DOT__RdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"RdM", &(TOP.top__DOT__pipeline_EM__DOT__RdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"RegWriteE", &(TOP.top__DOT__pipeline_EM__DOT__RegWriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"RegWriteM", &(TOP.top__DOT__pipeline_EM__DOT__RegWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"ResultSrcE", &(TOP.top__DOT__pipeline_EM__DOT__ResultSrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"ResultSrcM", &(TOP.top__DOT__pipeline_EM__DOT__ResultSrcM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_EM__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"WriteDataE", &(TOP.top__DOT__pipeline_EM__DOT__WriteDataE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"WriteDataM", &(TOP.top__DOT__pipeline_EM__DOT__WriteDataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"clk", &(TOP.top__DOT__pipeline_EM__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"modeAddrE", &(TOP.top__DOT__pipeline_EM__DOT__modeAddrE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__pipeline_EM.varInsert(__Vfinal,"modeAddrM", &(TOP.top__DOT__pipeline_EM__DOT__modeAddrM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_FD__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"InstrD", &(TOP.top__DOT__pipeline_FD__DOT__InstrD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"PCD", &(TOP.top__DOT__pipeline_FD__DOT__PCD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"PCF", &(TOP.top__DOT__pipeline_FD__DOT__PCF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"PCPlus4D", &(TOP.top__DOT__pipeline_FD__DOT__PCPlus4D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"PCPlus4F", &(TOP.top__DOT__pipeline_FD__DOT__PCPlus4F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"RD", &(TOP.top__DOT__pipeline_FD__DOT__RD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"clk", &(TOP.top__DOT__pipeline_FD__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"flush", &(TOP.top__DOT__pipeline_FD__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_FD.varInsert(__Vfinal,"stall", &(TOP.top__DOT__pipeline_FD__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ALUResultM", &(TOP.top__DOT__pipeline_MW__DOT__ALUResultM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ALUResultW", &(TOP.top__DOT__pipeline_MW__DOT__ALUResultW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_MW__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"InstrM", &(TOP.top__DOT__pipeline_MW__DOT__InstrM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"InstrW", &(TOP.top__DOT__pipeline_MW__DOT__InstrW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"PCPlus4M", &(TOP.top__DOT__pipeline_MW__DOT__PCPlus4M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"PCPlus4W", &(TOP.top__DOT__pipeline_MW__DOT__PCPlus4W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"RdM", &(TOP.top__DOT__pipeline_MW__DOT__RdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"RdW", &(TOP.top__DOT__pipeline_MW__DOT__RdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ReadDataM", &(TOP.top__DOT__pipeline_MW__DOT__ReadDataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ReadDataW", &(TOP.top__DOT__pipeline_MW__DOT__ReadDataW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"RegWriteM", &(TOP.top__DOT__pipeline_MW__DOT__RegWriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"RegWriteW", &(TOP.top__DOT__pipeline_MW__DOT__RegWriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ResultSrcM", &(TOP.top__DOT__pipeline_MW__DOT__ResultSrcM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"ResultSrcW", &(TOP.top__DOT__pipeline_MW__DOT__ResultSrcW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__pipeline_MW__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__pipeline_MW.varInsert(__Vfinal,"clk", &(TOP.top__DOT__pipeline_MW__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"PC", &(TOP.top__DOT__program_counter__DOT__PC), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"PCF", &(TOP.top__DOT__program_counter__DOT__PCF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__program_counter__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"clk", &(TOP.top__DOT__program_counter__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"rst", &(TOP.top__DOT__program_counter__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__program_counter.varInsert(__Vfinal,"stall", &(TOP.top__DOT__program_counter__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"AD1", &(TOP.top__DOT__regfile__DOT__AD1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"AD2", &(TOP.top__DOT__regfile__DOT__AD2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"AD3", &(TOP.top__DOT__regfile__DOT__AD3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"ADDRESS_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__regfile__DOT__ADDRESS_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__regfile__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"RD1", &(TOP.top__DOT__regfile__DOT__RD1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"RD2", &(TOP.top__DOT__regfile__DOT__RD2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"WD3", &(TOP.top__DOT__regfile__DOT__WD3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"WE3", &(TOP.top__DOT__regfile__DOT__WE3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a0", &(TOP.top__DOT__regfile__DOT__a0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a1", &(TOP.top__DOT__regfile__DOT__a1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a2", &(TOP.top__DOT__regfile__DOT__a2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a3", &(TOP.top__DOT__regfile__DOT__a3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a4", &(TOP.top__DOT__regfile__DOT__a4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a5", &(TOP.top__DOT__regfile__DOT__a5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a6", &(TOP.top__DOT__regfile__DOT__a6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"a7", &(TOP.top__DOT__regfile__DOT__a7), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"clk", &(TOP.top__DOT__regfile__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"registerfile_array", &(TOP.top__DOT__regfile__DOT__registerfile_array), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s0", &(TOP.top__DOT__regfile__DOT__s0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s1", &(TOP.top__DOT__regfile__DOT__s1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s10", &(TOP.top__DOT__regfile__DOT__s10), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s11", &(TOP.top__DOT__regfile__DOT__s11), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s2", &(TOP.top__DOT__regfile__DOT__s2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s3", &(TOP.top__DOT__regfile__DOT__s3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s4", &(TOP.top__DOT__regfile__DOT__s4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s5", &(TOP.top__DOT__regfile__DOT__s5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s6", &(TOP.top__DOT__regfile__DOT__s6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s7", &(TOP.top__DOT__regfile__DOT__s7), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s8", &(TOP.top__DOT__regfile__DOT__s8), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"s9", &(TOP.top__DOT__regfile__DOT__s9), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t0", &(TOP.top__DOT__regfile__DOT__t0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t1", &(TOP.top__DOT__regfile__DOT__t1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t2", &(TOP.top__DOT__regfile__DOT__t2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t3", &(TOP.top__DOT__regfile__DOT__t3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t4", &(TOP.top__DOT__regfile__DOT__t4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t5", &(TOP.top__DOT__regfile__DOT__t5), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile.varInsert(__Vfinal,"t6", &(TOP.top__DOT__regfile__DOT__t6), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__regfile_mux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"in0", &(TOP.top__DOT__regfile_mux__DOT__in0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"in1", &(TOP.top__DOT__regfile_mux__DOT__in1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"in2", &(TOP.top__DOT__regfile_mux__DOT__in2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"out", &(TOP.top__DOT__regfile_mux__DOT__out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__regfile_mux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__regfile_mux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__sign_extend.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__sign_extend__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__sign_extend.varInsert(__Vfinal,"ImmExt", &(TOP.top__DOT__sign_extend__DOT__ImmExt), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__sign_extend.varInsert(__Vfinal,"ImmInput", &(TOP.top__DOT__sign_extend__DOT__ImmInput), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__sign_extend.varInsert(__Vfinal,"ImmSrc", &(TOP.top__DOT__sign_extend__DOT__ImmSrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
    }
}
