// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"a0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"a1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+5,0,"a2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"a3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"a4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"a5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"a6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+10,0,"a7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"t0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"t1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"t2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"t3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+15,0,"t4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+16,0,"t5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"t6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+18,0,"s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+20,0,"s2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"s3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"s4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+23,0,"s5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+24,0,"s6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"s7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+26,0,"s8",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"s9",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"s10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+29,0,"s11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+30,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"a0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+33,0,"a1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+34,0,"a2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"a3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+36,0,"a4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,0,"a5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+38,0,"a6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+39,0,"a7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+40,0,"t0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+41,0,"t1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+42,0,"t2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+43,0,"t3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"t4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"t5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+46,0,"t6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+48,0,"s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"s2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"s3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,0,"s4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"s5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+53,0,"s6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+54,0,"s7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+55,0,"s8",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"s9",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+57,0,"s10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+58,0,"s11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+59,0,"InstrD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+60,0,"InstrF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+61,0,"InstrE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+62,0,"InstrM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+63,0,"InstrW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"RD1E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"RD2E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+66,0,"PCE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+67,0,"PCPlus4E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+68,0,"RegWriteE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"ALUSrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"MemWriteE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+71,0,"ResultSrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+72,0,"modeAddrE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+73,0,"RegWriteM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"MemWriteM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+75,0,"ResultSrcM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+76,0,"modeAddrM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+77,0,"ReadDataW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+78,0,"ReadDataM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+79,0,"RegWriteW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+80,0,"ResultSrcW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+81,0,"PCPlus4W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"ExtImmD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"ExtImmE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"ImmSrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+85,0,"RegWriteD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+86,0,"ALUControlD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+87,0,"ALUControlE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+88,0,"ALUSrcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+89,0,"ResultSrcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+90,0,"MemWriteD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+91,0,"modeAddrD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+92,0,"Zero",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+93,0,"MemReadD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"MemReadE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"JumpD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"JumpE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"BranchD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"BranchE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+99,0,"WriteDataE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"WriteDataM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"ALUResultM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"ALUResultE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"ALUResultW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"PCF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+106,0,"PCPlus4F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+107,0,"PCPlus4D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+108,0,"PCPlus4M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+109,0,"PCD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+110,0,"Rs1D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+111,0,"Rs1E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+112,0,"Rs2D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+113,0,"Rs2E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+114,0,"RdD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+115,0,"RdE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+116,0,"RdM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+117,0,"RdW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+118,0,"RD1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"RD2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+120,0,"RD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,0,"ResultW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+122,0,"SrcAE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+123,0,"ForwardAE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+124,0,"ForwardBE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+125,0,"flush",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"flushBranch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"BPU_Src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+129,0,"PC_predict",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"PC_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+380,0,"trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("BPU_mux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+131,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"in0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"in1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+134,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("PC_mux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+135,0,"ZeroE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"JumpE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"BranchE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+138,0,"PCPlus4F",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"ALUResult",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"PCTarget",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"PC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+381,0,"CONTROL_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+142,0,"SrcA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+143,0,"SrcB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+144,0,"ALUctrl",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"ALUResult",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+146,0,"ZeroE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("branch_prediction_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+147,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+148,0,"RD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"PCF",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+150,0,"ZeroE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"BranchE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"flushBranch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+153,0,"PCBPU",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+154,0,"PCBPUSrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+155,0,"newBranch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 65,0);
    tracep->declArray(c+158,0,"oldBranch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 65,0);
    tracep->declBus(c+161,0,"forwardJumpCounter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+162,0,"backwardJumpCounter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("control_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+163,0,"InstrD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+164,0,"ResultSrcD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+165,0,"MemWriteD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"JumpD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"BranchD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+168,0,"ALUControlD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+169,0,"ALUSrcD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+170,0,"ImmSrcD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+171,0,"RegWriteD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+172,0,"modeAddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+173,0,"MemReadD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+174,0,"op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+175,0,"funct3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 14,12);
    tracep->declBit(c+176,0,"funct7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+177,0,"ALUOp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+178,0,"Store",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+179,0,"Load",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("alu_decoder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+180,0,"ALUOp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+181,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+182,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+183,0,"funct7",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+184,0,"ALUControl",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("data_memory", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+185,0,"modeAddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+186,0,"ResultSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+187,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+188,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+189,0,"WD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+190,0,"trigger",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+191,0,"WE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+192,0,"RD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("forwardAE_mux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+193,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+194,0,"in0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+195,0,"in1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+196,0,"in2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+197,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("forwardBE_mux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+198,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+199,0,"in0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+200,0,"in1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,0,"in2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("hazard_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+382,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"RdM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+204,0,"RdW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+205,0,"RdE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+206,0,"Rs1E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+207,0,"Rs2E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+208,0,"RegWriteM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"RegWriteW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+210,0,"MemReadE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+211,0,"flushBranch",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+212,0,"ForwardAE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+213,0,"ForwardBE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+214,0,"stall",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"flush",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("instruction_memory", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+216,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+217,0,"instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pipeline_DE", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+382,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+218,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"flush",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"MemReadD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"MemReadE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"RegWriteD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+223,0,"RegWriteE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+224,0,"ResultSrcD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+225,0,"ResultSrcE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+226,0,"MemWriteD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"MemWriteE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"JumpD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"JumpE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"BranchD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"BranchE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+232,0,"ALUControlD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+233,0,"ALUControlE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+234,0,"ALUSrcD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"ALUSrcE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+236,0,"RD1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+237,0,"RD1E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+238,0,"RD2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+239,0,"RD2E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+240,0,"PCD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+241,0,"PCE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+242,0,"Rs1D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+243,0,"Rs1E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+244,0,"Rs2D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+245,0,"Rs2E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+246,0,"RdD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+247,0,"RdE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+248,0,"ExtImmD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+249,0,"ExtImmE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+250,0,"PCPlus4D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+251,0,"PCPlus4E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+252,0,"modeAddrD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+253,0,"modeAddrE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+254,0,"InstrD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+255,0,"InstrE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pipeline_EM", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+382,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"RegWriteE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+258,0,"RegWriteM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+259,0,"ResultSrcE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+260,0,"ResultSrcM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+261,0,"MemWriteE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+262,0,"MemWriteM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+263,0,"ALUResultE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"ALUResultM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+265,0,"WriteDataE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+266,0,"WriteDataM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+267,0,"RdE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+268,0,"RdM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+269,0,"PCPlus4E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+270,0,"PCPlus4M",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+271,0,"modeAddrE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+272,0,"modeAddrM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+273,0,"InstrE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+274,0,"InstrM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pipeline_FD", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+275,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"flush",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"stall",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+278,0,"RD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+279,0,"InstrD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+280,0,"PCF",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+281,0,"PCD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+282,0,"PCPlus4F",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+283,0,"PCPlus4D",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pipeline_MW", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+382,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+284,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"RegWriteM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+286,0,"RegWriteW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+287,0,"ResultSrcM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+288,0,"ResultSrcW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+289,0,"ALUResultM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+290,0,"ALUResultW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+291,0,"ReadDataM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+292,0,"ReadDataW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+293,0,"RdM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+294,0,"RdW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+295,0,"PCPlus4M",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+296,0,"PCPlus4W",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+297,0,"InstrM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"InstrW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("program_counter", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+299,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+300,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+301,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+302,0,"stall",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+303,0,"PCF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regfile", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+382,0,"ADDRESS_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+304,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+305,0,"AD1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+306,0,"AD2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+307,0,"AD3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+308,0,"WE3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+309,0,"WD3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+310,0,"RD1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+311,0,"RD2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+312,0,"a0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+313,0,"a1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+314,0,"a2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+315,0,"a3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+316,0,"a4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+317,0,"a5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+318,0,"a6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+319,0,"a7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+320,0,"t0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+321,0,"t1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+322,0,"t2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+323,0,"t3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+324,0,"t4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+325,0,"t5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+326,0,"t6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+327,0,"s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+328,0,"s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+329,0,"s2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+330,0,"s3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+331,0,"s4",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+332,0,"s5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+333,0,"s6",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+334,0,"s7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+335,0,"s8",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+336,0,"s9",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+337,0,"s10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+338,0,"s11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("registerfile_array", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+339+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("regfile_mux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+371,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+372,0,"in0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+373,0,"in1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+374,0,"in2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+375,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("sign_extend", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+379,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+376,0,"ImmSrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+377,0,"ImmInput",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+378,0,"ImmExt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+379,(0x20U),32);
    bufp->fullBit(oldp+380,(vlSelfRef.top__DOT__trigger));
    bufp->fullIData(oldp+381,(4U),32);
    bufp->fullIData(oldp+382,(5U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullIData(oldp+3,(vlSelfRef.a0),32);
    bufp->fullIData(oldp+4,(vlSelfRef.a1),32);
    bufp->fullIData(oldp+5,(vlSelfRef.a2),32);
    bufp->fullIData(oldp+6,(vlSelfRef.a3),32);
    bufp->fullIData(oldp+7,(vlSelfRef.a4),32);
    bufp->fullIData(oldp+8,(vlSelfRef.a5),32);
    bufp->fullIData(oldp+9,(vlSelfRef.a6),32);
    bufp->fullIData(oldp+10,(vlSelfRef.a7),32);
    bufp->fullIData(oldp+11,(vlSelfRef.t0),32);
    bufp->fullIData(oldp+12,(vlSelfRef.t1),32);
    bufp->fullIData(oldp+13,(vlSelfRef.t2),32);
    bufp->fullIData(oldp+14,(vlSelfRef.t3),32);
    bufp->fullIData(oldp+15,(vlSelfRef.t4),32);
    bufp->fullIData(oldp+16,(vlSelfRef.t5),32);
    bufp->fullIData(oldp+17,(vlSelfRef.t6),32);
    bufp->fullIData(oldp+18,(vlSelfRef.s0),32);
    bufp->fullIData(oldp+19,(vlSelfRef.s1),32);
    bufp->fullIData(oldp+20,(vlSelfRef.s2),32);
    bufp->fullIData(oldp+21,(vlSelfRef.s3),32);
    bufp->fullIData(oldp+22,(vlSelfRef.s4),32);
    bufp->fullIData(oldp+23,(vlSelfRef.s5),32);
    bufp->fullIData(oldp+24,(vlSelfRef.s6),32);
    bufp->fullIData(oldp+25,(vlSelfRef.s7),32);
    bufp->fullIData(oldp+26,(vlSelfRef.s8),32);
    bufp->fullIData(oldp+27,(vlSelfRef.s9),32);
    bufp->fullIData(oldp+28,(vlSelfRef.s10),32);
    bufp->fullIData(oldp+29,(vlSelfRef.s11),32);
    bufp->fullBit(oldp+30,(vlSelfRef.top__DOT__clk));
    bufp->fullBit(oldp+31,(vlSelfRef.top__DOT__rst));
    bufp->fullIData(oldp+32,(vlSelfRef.top__DOT__a0),32);
    bufp->fullIData(oldp+33,(vlSelfRef.top__DOT__a1),32);
    bufp->fullIData(oldp+34,(vlSelfRef.top__DOT__a2),32);
    bufp->fullIData(oldp+35,(vlSelfRef.top__DOT__a3),32);
    bufp->fullIData(oldp+36,(vlSelfRef.top__DOT__a4),32);
    bufp->fullIData(oldp+37,(vlSelfRef.top__DOT__a5),32);
    bufp->fullIData(oldp+38,(vlSelfRef.top__DOT__a6),32);
    bufp->fullIData(oldp+39,(vlSelfRef.top__DOT__a7),32);
    bufp->fullIData(oldp+40,(vlSelfRef.top__DOT__t0),32);
    bufp->fullIData(oldp+41,(vlSelfRef.top__DOT__t1),32);
    bufp->fullIData(oldp+42,(vlSelfRef.top__DOT__t2),32);
    bufp->fullIData(oldp+43,(vlSelfRef.top__DOT__t3),32);
    bufp->fullIData(oldp+44,(vlSelfRef.top__DOT__t4),32);
    bufp->fullIData(oldp+45,(vlSelfRef.top__DOT__t5),32);
    bufp->fullIData(oldp+46,(vlSelfRef.top__DOT__t6),32);
    bufp->fullIData(oldp+47,(vlSelfRef.top__DOT__s0),32);
    bufp->fullIData(oldp+48,(vlSelfRef.top__DOT__s1),32);
    bufp->fullIData(oldp+49,(vlSelfRef.top__DOT__s2),32);
    bufp->fullIData(oldp+50,(vlSelfRef.top__DOT__s3),32);
    bufp->fullIData(oldp+51,(vlSelfRef.top__DOT__s4),32);
    bufp->fullIData(oldp+52,(vlSelfRef.top__DOT__s5),32);
    bufp->fullIData(oldp+53,(vlSelfRef.top__DOT__s6),32);
    bufp->fullIData(oldp+54,(vlSelfRef.top__DOT__s7),32);
    bufp->fullIData(oldp+55,(vlSelfRef.top__DOT__s8),32);
    bufp->fullIData(oldp+56,(vlSelfRef.top__DOT__s9),32);
    bufp->fullIData(oldp+57,(vlSelfRef.top__DOT__s10),32);
    bufp->fullIData(oldp+58,(vlSelfRef.top__DOT__s11),32);
    bufp->fullIData(oldp+59,(vlSelfRef.top__DOT__InstrD),32);
    bufp->fullIData(oldp+60,(vlSelfRef.top__DOT__InstrF),32);
    bufp->fullIData(oldp+61,(vlSelfRef.top__DOT__InstrE),32);
    bufp->fullIData(oldp+62,(vlSelfRef.top__DOT__InstrM),32);
    bufp->fullIData(oldp+63,(vlSelfRef.top__DOT__InstrW),32);
    bufp->fullIData(oldp+64,(vlSelfRef.top__DOT__RD1E),32);
    bufp->fullIData(oldp+65,(vlSelfRef.top__DOT__RD2E),32);
    bufp->fullIData(oldp+66,(vlSelfRef.top__DOT__PCE),32);
    bufp->fullIData(oldp+67,(vlSelfRef.top__DOT__PCPlus4E),32);
    bufp->fullBit(oldp+68,(vlSelfRef.top__DOT__RegWriteE));
    bufp->fullBit(oldp+69,(vlSelfRef.top__DOT__ALUSrcE));
    bufp->fullBit(oldp+70,(vlSelfRef.top__DOT__MemWriteE));
    bufp->fullCData(oldp+71,(vlSelfRef.top__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+72,(vlSelfRef.top__DOT__modeAddrE),3);
    bufp->fullBit(oldp+73,(vlSelfRef.top__DOT__RegWriteM));
    bufp->fullBit(oldp+74,(vlSelfRef.top__DOT__MemWriteM));
    bufp->fullCData(oldp+75,(vlSelfRef.top__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+76,(vlSelfRef.top__DOT__modeAddrM),3);
    bufp->fullIData(oldp+77,(vlSelfRef.top__DOT__ReadDataW),32);
    bufp->fullIData(oldp+78,(vlSelfRef.top__DOT__ReadDataM),32);
    bufp->fullBit(oldp+79,(vlSelfRef.top__DOT__RegWriteW));
    bufp->fullCData(oldp+80,(vlSelfRef.top__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+81,(vlSelfRef.top__DOT__PCPlus4W),32);
    bufp->fullIData(oldp+82,(vlSelfRef.top__DOT__ExtImmD),32);
    bufp->fullIData(oldp+83,(vlSelfRef.top__DOT__ExtImmE),32);
    bufp->fullCData(oldp+84,(vlSelfRef.top__DOT__ImmSrc),3);
    bufp->fullBit(oldp+85,(vlSelfRef.top__DOT__RegWriteD));
    bufp->fullCData(oldp+86,(vlSelfRef.top__DOT__ALUControlD),4);
    bufp->fullCData(oldp+87,(vlSelfRef.top__DOT__ALUControlE),4);
    bufp->fullBit(oldp+88,(vlSelfRef.top__DOT__ALUSrcD));
    bufp->fullCData(oldp+89,(vlSelfRef.top__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+90,(vlSelfRef.top__DOT__MemWriteD));
    bufp->fullCData(oldp+91,(vlSelfRef.top__DOT__modeAddrD),3);
    bufp->fullBit(oldp+92,(vlSelfRef.top__DOT__Zero));
    bufp->fullBit(oldp+93,(vlSelfRef.top__DOT__MemReadD));
    bufp->fullBit(oldp+94,(vlSelfRef.top__DOT__MemReadE));
    bufp->fullBit(oldp+95,(vlSelfRef.top__DOT__JumpD));
    bufp->fullBit(oldp+96,(vlSelfRef.top__DOT__JumpE));
    bufp->fullBit(oldp+97,(vlSelfRef.top__DOT__BranchD));
    bufp->fullBit(oldp+98,(vlSelfRef.top__DOT__BranchE));
    bufp->fullIData(oldp+99,(vlSelfRef.top__DOT__WriteDataE),32);
    bufp->fullIData(oldp+100,(vlSelfRef.top__DOT__WriteDataM),32);
    bufp->fullIData(oldp+101,(vlSelfRef.top__DOT__ALUResultM),32);
    bufp->fullIData(oldp+102,(vlSelfRef.top__DOT__ALUResultE),32);
    bufp->fullIData(oldp+103,(vlSelfRef.top__DOT__ALUResultW),32);
    bufp->fullIData(oldp+104,(vlSelfRef.top__DOT__PC),32);
    bufp->fullIData(oldp+105,(vlSelfRef.top__DOT__PCF),32);
    bufp->fullIData(oldp+106,(vlSelfRef.top__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+107,(vlSelfRef.top__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+108,(vlSelfRef.top__DOT__PCPlus4M),32);
    bufp->fullIData(oldp+109,(vlSelfRef.top__DOT__PCD),32);
    bufp->fullCData(oldp+110,(vlSelfRef.top__DOT__Rs1D),5);
    bufp->fullCData(oldp+111,(vlSelfRef.top__DOT__Rs1E),5);
    bufp->fullCData(oldp+112,(vlSelfRef.top__DOT__Rs2D),5);
    bufp->fullCData(oldp+113,(vlSelfRef.top__DOT__Rs2E),5);
    bufp->fullCData(oldp+114,(vlSelfRef.top__DOT__RdD),5);
    bufp->fullCData(oldp+115,(vlSelfRef.top__DOT__RdE),5);
    bufp->fullCData(oldp+116,(vlSelfRef.top__DOT__RdM),5);
    bufp->fullCData(oldp+117,(vlSelfRef.top__DOT__RdW),5);
    bufp->fullIData(oldp+118,(vlSelfRef.top__DOT__RD1),32);
    bufp->fullIData(oldp+119,(vlSelfRef.top__DOT__RD2),32);
    bufp->fullIData(oldp+120,(vlSelfRef.top__DOT__RD),32);
    bufp->fullIData(oldp+121,(vlSelfRef.top__DOT__ResultW),32);
    bufp->fullIData(oldp+122,(vlSelfRef.top__DOT__SrcAE),32);
    bufp->fullCData(oldp+123,(vlSelfRef.top__DOT__ForwardAE),2);
    bufp->fullCData(oldp+124,(vlSelfRef.top__DOT__ForwardBE),2);
    bufp->fullBit(oldp+125,(vlSelfRef.top__DOT__flush));
    bufp->fullBit(oldp+126,(vlSelfRef.top__DOT__stall));
    bufp->fullBit(oldp+127,(vlSelfRef.top__DOT__flushBranch));
    bufp->fullBit(oldp+128,(vlSelfRef.top__DOT__BPU_Src));
    bufp->fullIData(oldp+129,(vlSelfRef.top__DOT__PC_predict),32);
    bufp->fullIData(oldp+130,(vlSelfRef.top__DOT__PC_next),32);
    bufp->fullBit(oldp+131,(vlSelfRef.top__DOT__BPU_mux__DOT__sel));
    bufp->fullIData(oldp+132,(vlSelfRef.top__DOT__BPU_mux__DOT__in0),32);
    bufp->fullIData(oldp+133,(vlSelfRef.top__DOT__BPU_mux__DOT__in1),32);
    bufp->fullIData(oldp+134,(vlSelfRef.top__DOT__BPU_mux__DOT__out),32);
    bufp->fullBit(oldp+135,(vlSelfRef.top__DOT__PC_mux__DOT__ZeroE));
    bufp->fullBit(oldp+136,(vlSelfRef.top__DOT__PC_mux__DOT__JumpE));
    bufp->fullBit(oldp+137,(vlSelfRef.top__DOT__PC_mux__DOT__BranchE));
    bufp->fullIData(oldp+138,(vlSelfRef.top__DOT__PC_mux__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+139,(vlSelfRef.top__DOT__PC_mux__DOT__ALUResult),32);
    bufp->fullIData(oldp+140,(vlSelfRef.top__DOT__PC_mux__DOT__PCTarget),32);
    bufp->fullIData(oldp+141,(vlSelfRef.top__DOT__PC_mux__DOT__PC),32);
    bufp->fullIData(oldp+142,(vlSelfRef.top__DOT__alu__DOT__SrcA),32);
    bufp->fullIData(oldp+143,(vlSelfRef.top__DOT__alu__DOT__SrcB),32);
    bufp->fullCData(oldp+144,(vlSelfRef.top__DOT__alu__DOT__ALUctrl),4);
    bufp->fullIData(oldp+145,(vlSelfRef.top__DOT__alu__DOT__ALUResult),32);
    bufp->fullBit(oldp+146,(vlSelfRef.top__DOT__alu__DOT__ZeroE));
    bufp->fullBit(oldp+147,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__clk));
    bufp->fullIData(oldp+148,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__RD),32);
    bufp->fullIData(oldp+149,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__PCF),32);
    bufp->fullBit(oldp+150,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__ZeroE));
    bufp->fullBit(oldp+151,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__BranchE));
    bufp->fullBit(oldp+152,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__flushBranch));
    bufp->fullIData(oldp+153,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__PCBPU),32);
    bufp->fullBit(oldp+154,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__PCBPUSrc));
    bufp->fullWData(oldp+155,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__newBranch),66);
    bufp->fullWData(oldp+158,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__oldBranch),66);
    bufp->fullCData(oldp+161,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__forwardJumpCounter),2);
    bufp->fullCData(oldp+162,(vlSelfRef.top__DOT__branch_prediction_unit__DOT__backwardJumpCounter),2);
    bufp->fullIData(oldp+163,(vlSelfRef.top__DOT__control_unit__DOT__InstrD),32);
    bufp->fullCData(oldp+164,(vlSelfRef.top__DOT__control_unit__DOT__ResultSrcD),2);
    bufp->fullBit(oldp+165,(vlSelfRef.top__DOT__control_unit__DOT__MemWriteD));
    bufp->fullBit(oldp+166,(vlSelfRef.top__DOT__control_unit__DOT__JumpD));
    bufp->fullBit(oldp+167,(vlSelfRef.top__DOT__control_unit__DOT__BranchD));
    bufp->fullCData(oldp+168,(vlSelfRef.top__DOT__control_unit__DOT__ALUControlD),4);
    bufp->fullBit(oldp+169,(vlSelfRef.top__DOT__control_unit__DOT__ALUSrcD));
    bufp->fullCData(oldp+170,(vlSelfRef.top__DOT__control_unit__DOT__ImmSrcD),3);
    bufp->fullBit(oldp+171,(vlSelfRef.top__DOT__control_unit__DOT__RegWriteD));
    bufp->fullCData(oldp+172,(vlSelfRef.top__DOT__control_unit__DOT__modeAddr),3);
    bufp->fullBit(oldp+173,(vlSelfRef.top__DOT__control_unit__DOT__MemReadD));
    bufp->fullCData(oldp+174,(vlSelfRef.top__DOT__control_unit__DOT__op),7);
    bufp->fullCData(oldp+175,(vlSelfRef.top__DOT__control_unit__DOT__funct3),3);
    bufp->fullBit(oldp+176,(vlSelfRef.top__DOT__control_unit__DOT__funct7));
    bufp->fullCData(oldp+177,(vlSelfRef.top__DOT__control_unit__DOT__ALUOp),2);
    bufp->fullBit(oldp+178,(vlSelfRef.top__DOT__control_unit__DOT__Store));
    bufp->fullBit(oldp+179,(vlSelfRef.top__DOT__control_unit__DOT__Load));
    bufp->fullCData(oldp+180,(vlSelfRef.top__DOT__control_unit__DOT__alu_decoder__DOT__ALUOp),2);
    bufp->fullBit(oldp+181,(vlSelfRef.top__DOT__control_unit__DOT__alu_decoder__DOT__op));
    bufp->fullCData(oldp+182,(vlSelfRef.top__DOT__control_unit__DOT__alu_decoder__DOT__funct3),3);
    bufp->fullBit(oldp+183,(vlSelfRef.top__DOT__control_unit__DOT__alu_decoder__DOT__funct7));
    bufp->fullCData(oldp+184,(vlSelfRef.top__DOT__control_unit__DOT__alu_decoder__DOT__ALUControl),4);
    bufp->fullCData(oldp+185,(vlSelfRef.top__DOT__data_memory__DOT__modeAddr),3);
    bufp->fullCData(oldp+186,(vlSelfRef.top__DOT__data_memory__DOT__ResultSrc),2);
    bufp->fullBit(oldp+187,(vlSelfRef.top__DOT__data_memory__DOT__clk));
    bufp->fullIData(oldp+188,(vlSelfRef.top__DOT__data_memory__DOT__A),32);
    bufp->fullIData(oldp+189,(vlSelfRef.top__DOT__data_memory__DOT__WD),32);
    bufp->fullBit(oldp+190,(vlSelfRef.top__DOT__data_memory__DOT__trigger));
    bufp->fullBit(oldp+191,(vlSelfRef.top__DOT__data_memory__DOT__WE));
    bufp->fullIData(oldp+192,(vlSelfRef.top__DOT__data_memory__DOT__RD),32);
    bufp->fullCData(oldp+193,(vlSelfRef.top__DOT__forwardAE_mux__DOT__sel),2);
    bufp->fullIData(oldp+194,(vlSelfRef.top__DOT__forwardAE_mux__DOT__in0),32);
    bufp->fullIData(oldp+195,(vlSelfRef.top__DOT__forwardAE_mux__DOT__in1),32);
    bufp->fullIData(oldp+196,(vlSelfRef.top__DOT__forwardAE_mux__DOT__in2),32);
    bufp->fullIData(oldp+197,(vlSelfRef.top__DOT__forwardAE_mux__DOT__out),32);
    bufp->fullCData(oldp+198,(vlSelfRef.top__DOT__forwardBE_mux__DOT__sel),2);
    bufp->fullIData(oldp+199,(vlSelfRef.top__DOT__forwardBE_mux__DOT__in0),32);
    bufp->fullIData(oldp+200,(vlSelfRef.top__DOT__forwardBE_mux__DOT__in1),32);
    bufp->fullIData(oldp+201,(vlSelfRef.top__DOT__forwardBE_mux__DOT__in2),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top__DOT__forwardBE_mux__DOT__out),32);
    bufp->fullCData(oldp+203,(vlSelfRef.top__DOT__hazard_unit__DOT__RdM),5);
    bufp->fullCData(oldp+204,(vlSelfRef.top__DOT__hazard_unit__DOT__RdW),5);
    bufp->fullCData(oldp+205,(vlSelfRef.top__DOT__hazard_unit__DOT__RdE),5);
    bufp->fullCData(oldp+206,(vlSelfRef.top__DOT__hazard_unit__DOT__Rs1E),5);
    bufp->fullCData(oldp+207,(vlSelfRef.top__DOT__hazard_unit__DOT__Rs2E),5);
    bufp->fullBit(oldp+208,(vlSelfRef.top__DOT__hazard_unit__DOT__RegWriteM));
    bufp->fullBit(oldp+209,(vlSelfRef.top__DOT__hazard_unit__DOT__RegWriteW));
    bufp->fullBit(oldp+210,(vlSelfRef.top__DOT__hazard_unit__DOT__MemReadE));
    bufp->fullBit(oldp+211,(vlSelfRef.top__DOT__hazard_unit__DOT__flushBranch));
    bufp->fullCData(oldp+212,(vlSelfRef.top__DOT__hazard_unit__DOT__ForwardAE),2);
    bufp->fullCData(oldp+213,(vlSelfRef.top__DOT__hazard_unit__DOT__ForwardBE),2);
    bufp->fullBit(oldp+214,(vlSelfRef.top__DOT__hazard_unit__DOT__stall));
    bufp->fullBit(oldp+215,(vlSelfRef.top__DOT__hazard_unit__DOT__flush));
    bufp->fullIData(oldp+216,(vlSelfRef.top__DOT__instruction_memory__DOT__PC),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top__DOT__instruction_memory__DOT__instr),32);
    bufp->fullBit(oldp+218,(vlSelfRef.top__DOT__pipeline_DE__DOT__clk));
    bufp->fullBit(oldp+219,(vlSelfRef.top__DOT__pipeline_DE__DOT__flush));
    bufp->fullBit(oldp+220,(vlSelfRef.top__DOT__pipeline_DE__DOT__MemReadD));
    bufp->fullBit(oldp+221,(vlSelfRef.top__DOT__pipeline_DE__DOT__MemReadE));
    bufp->fullBit(oldp+222,(vlSelfRef.top__DOT__pipeline_DE__DOT__RegWriteD));
    bufp->fullBit(oldp+223,(vlSelfRef.top__DOT__pipeline_DE__DOT__RegWriteE));
    bufp->fullCData(oldp+224,(vlSelfRef.top__DOT__pipeline_DE__DOT__ResultSrcD),2);
    bufp->fullCData(oldp+225,(vlSelfRef.top__DOT__pipeline_DE__DOT__ResultSrcE),2);
    bufp->fullBit(oldp+226,(vlSelfRef.top__DOT__pipeline_DE__DOT__MemWriteD));
    bufp->fullBit(oldp+227,(vlSelfRef.top__DOT__pipeline_DE__DOT__MemWriteE));
    bufp->fullBit(oldp+228,(vlSelfRef.top__DOT__pipeline_DE__DOT__JumpD));
    bufp->fullBit(oldp+229,(vlSelfRef.top__DOT__pipeline_DE__DOT__JumpE));
    bufp->fullBit(oldp+230,(vlSelfRef.top__DOT__pipeline_DE__DOT__BranchD));
    bufp->fullBit(oldp+231,(vlSelfRef.top__DOT__pipeline_DE__DOT__BranchE));
    bufp->fullCData(oldp+232,(vlSelfRef.top__DOT__pipeline_DE__DOT__ALUControlD),4);
    bufp->fullCData(oldp+233,(vlSelfRef.top__DOT__pipeline_DE__DOT__ALUControlE),4);
    bufp->fullBit(oldp+234,(vlSelfRef.top__DOT__pipeline_DE__DOT__ALUSrcD));
    bufp->fullBit(oldp+235,(vlSelfRef.top__DOT__pipeline_DE__DOT__ALUSrcE));
    bufp->fullIData(oldp+236,(vlSelfRef.top__DOT__pipeline_DE__DOT__RD1),32);
    bufp->fullIData(oldp+237,(vlSelfRef.top__DOT__pipeline_DE__DOT__RD1E),32);
    bufp->fullIData(oldp+238,(vlSelfRef.top__DOT__pipeline_DE__DOT__RD2),32);
    bufp->fullIData(oldp+239,(vlSelfRef.top__DOT__pipeline_DE__DOT__RD2E),32);
    bufp->fullIData(oldp+240,(vlSelfRef.top__DOT__pipeline_DE__DOT__PCD),32);
    bufp->fullIData(oldp+241,(vlSelfRef.top__DOT__pipeline_DE__DOT__PCE),32);
    bufp->fullCData(oldp+242,(vlSelfRef.top__DOT__pipeline_DE__DOT__Rs1D),5);
    bufp->fullCData(oldp+243,(vlSelfRef.top__DOT__pipeline_DE__DOT__Rs1E),5);
    bufp->fullCData(oldp+244,(vlSelfRef.top__DOT__pipeline_DE__DOT__Rs2D),5);
    bufp->fullCData(oldp+245,(vlSelfRef.top__DOT__pipeline_DE__DOT__Rs2E),5);
    bufp->fullCData(oldp+246,(vlSelfRef.top__DOT__pipeline_DE__DOT__RdD),5);
    bufp->fullCData(oldp+247,(vlSelfRef.top__DOT__pipeline_DE__DOT__RdE),5);
    bufp->fullIData(oldp+248,(vlSelfRef.top__DOT__pipeline_DE__DOT__ExtImmD),32);
    bufp->fullIData(oldp+249,(vlSelfRef.top__DOT__pipeline_DE__DOT__ExtImmE),32);
    bufp->fullIData(oldp+250,(vlSelfRef.top__DOT__pipeline_DE__DOT__PCPlus4D),32);
    bufp->fullIData(oldp+251,(vlSelfRef.top__DOT__pipeline_DE__DOT__PCPlus4E),32);
    bufp->fullCData(oldp+252,(vlSelfRef.top__DOT__pipeline_DE__DOT__modeAddrD),3);
    bufp->fullCData(oldp+253,(vlSelfRef.top__DOT__pipeline_DE__DOT__modeAddrE),3);
    bufp->fullIData(oldp+254,(vlSelfRef.top__DOT__pipeline_DE__DOT__InstrD),32);
    bufp->fullIData(oldp+255,(vlSelfRef.top__DOT__pipeline_DE__DOT__InstrE),32);
    bufp->fullBit(oldp+256,(vlSelfRef.top__DOT__pipeline_EM__DOT__clk));
    bufp->fullBit(oldp+257,(vlSelfRef.top__DOT__pipeline_EM__DOT__RegWriteE));
    bufp->fullBit(oldp+258,(vlSelfRef.top__DOT__pipeline_EM__DOT__RegWriteM));
    bufp->fullCData(oldp+259,(vlSelfRef.top__DOT__pipeline_EM__DOT__ResultSrcE),2);
    bufp->fullCData(oldp+260,(vlSelfRef.top__DOT__pipeline_EM__DOT__ResultSrcM),2);
    bufp->fullBit(oldp+261,(vlSelfRef.top__DOT__pipeline_EM__DOT__MemWriteE));
    bufp->fullBit(oldp+262,(vlSelfRef.top__DOT__pipeline_EM__DOT__MemWriteM));
    bufp->fullIData(oldp+263,(vlSelfRef.top__DOT__pipeline_EM__DOT__ALUResultE),32);
    bufp->fullIData(oldp+264,(vlSelfRef.top__DOT__pipeline_EM__DOT__ALUResultM),32);
    bufp->fullIData(oldp+265,(vlSelfRef.top__DOT__pipeline_EM__DOT__WriteDataE),32);
    bufp->fullIData(oldp+266,(vlSelfRef.top__DOT__pipeline_EM__DOT__WriteDataM),32);
    bufp->fullCData(oldp+267,(vlSelfRef.top__DOT__pipeline_EM__DOT__RdE),5);
    bufp->fullCData(oldp+268,(vlSelfRef.top__DOT__pipeline_EM__DOT__RdM),5);
    bufp->fullIData(oldp+269,(vlSelfRef.top__DOT__pipeline_EM__DOT__PCPlus4E),32);
    bufp->fullIData(oldp+270,(vlSelfRef.top__DOT__pipeline_EM__DOT__PCPlus4M),32);
    bufp->fullCData(oldp+271,(vlSelfRef.top__DOT__pipeline_EM__DOT__modeAddrE),3);
    bufp->fullCData(oldp+272,(vlSelfRef.top__DOT__pipeline_EM__DOT__modeAddrM),3);
    bufp->fullIData(oldp+273,(vlSelfRef.top__DOT__pipeline_EM__DOT__InstrE),32);
    bufp->fullIData(oldp+274,(vlSelfRef.top__DOT__pipeline_EM__DOT__InstrM),32);
    bufp->fullBit(oldp+275,(vlSelfRef.top__DOT__pipeline_FD__DOT__clk));
    bufp->fullBit(oldp+276,(vlSelfRef.top__DOT__pipeline_FD__DOT__flush));
    bufp->fullBit(oldp+277,(vlSelfRef.top__DOT__pipeline_FD__DOT__stall));
    bufp->fullIData(oldp+278,(vlSelfRef.top__DOT__pipeline_FD__DOT__RD),32);
    bufp->fullIData(oldp+279,(vlSelfRef.top__DOT__pipeline_FD__DOT__InstrD),32);
    bufp->fullIData(oldp+280,(vlSelfRef.top__DOT__pipeline_FD__DOT__PCF),32);
    bufp->fullIData(oldp+281,(vlSelfRef.top__DOT__pipeline_FD__DOT__PCD),32);
    bufp->fullIData(oldp+282,(vlSelfRef.top__DOT__pipeline_FD__DOT__PCPlus4F),32);
    bufp->fullIData(oldp+283,(vlSelfRef.top__DOT__pipeline_FD__DOT__PCPlus4D),32);
    bufp->fullBit(oldp+284,(vlSelfRef.top__DOT__pipeline_MW__DOT__clk));
    bufp->fullBit(oldp+285,(vlSelfRef.top__DOT__pipeline_MW__DOT__RegWriteM));
    bufp->fullBit(oldp+286,(vlSelfRef.top__DOT__pipeline_MW__DOT__RegWriteW));
    bufp->fullCData(oldp+287,(vlSelfRef.top__DOT__pipeline_MW__DOT__ResultSrcM),2);
    bufp->fullCData(oldp+288,(vlSelfRef.top__DOT__pipeline_MW__DOT__ResultSrcW),2);
    bufp->fullIData(oldp+289,(vlSelfRef.top__DOT__pipeline_MW__DOT__ALUResultM),32);
    bufp->fullIData(oldp+290,(vlSelfRef.top__DOT__pipeline_MW__DOT__ALUResultW),32);
    bufp->fullIData(oldp+291,(vlSelfRef.top__DOT__pipeline_MW__DOT__ReadDataM),32);
    bufp->fullIData(oldp+292,(vlSelfRef.top__DOT__pipeline_MW__DOT__ReadDataW),32);
    bufp->fullCData(oldp+293,(vlSelfRef.top__DOT__pipeline_MW__DOT__RdM),5);
    bufp->fullCData(oldp+294,(vlSelfRef.top__DOT__pipeline_MW__DOT__RdW),5);
    bufp->fullIData(oldp+295,(vlSelfRef.top__DOT__pipeline_MW__DOT__PCPlus4M),32);
    bufp->fullIData(oldp+296,(vlSelfRef.top__DOT__pipeline_MW__DOT__PCPlus4W),32);
    bufp->fullIData(oldp+297,(vlSelfRef.top__DOT__pipeline_MW__DOT__InstrM),32);
    bufp->fullIData(oldp+298,(vlSelfRef.top__DOT__pipeline_MW__DOT__InstrW),32);
    bufp->fullBit(oldp+299,(vlSelfRef.top__DOT__program_counter__DOT__clk));
    bufp->fullBit(oldp+300,(vlSelfRef.top__DOT__program_counter__DOT__rst));
    bufp->fullIData(oldp+301,(vlSelfRef.top__DOT__program_counter__DOT__PC),32);
    bufp->fullBit(oldp+302,(vlSelfRef.top__DOT__program_counter__DOT__stall));
    bufp->fullIData(oldp+303,(vlSelfRef.top__DOT__program_counter__DOT__PCF),32);
    bufp->fullBit(oldp+304,(vlSelfRef.top__DOT__regfile__DOT__clk));
    bufp->fullCData(oldp+305,(vlSelfRef.top__DOT__regfile__DOT__AD1),5);
    bufp->fullCData(oldp+306,(vlSelfRef.top__DOT__regfile__DOT__AD2),5);
    bufp->fullCData(oldp+307,(vlSelfRef.top__DOT__regfile__DOT__AD3),5);
    bufp->fullBit(oldp+308,(vlSelfRef.top__DOT__regfile__DOT__WE3));
    bufp->fullIData(oldp+309,(vlSelfRef.top__DOT__regfile__DOT__WD3),32);
    bufp->fullIData(oldp+310,(vlSelfRef.top__DOT__regfile__DOT__RD1),32);
    bufp->fullIData(oldp+311,(vlSelfRef.top__DOT__regfile__DOT__RD2),32);
    bufp->fullIData(oldp+312,(vlSelfRef.top__DOT__regfile__DOT__a0),32);
    bufp->fullIData(oldp+313,(vlSelfRef.top__DOT__regfile__DOT__a1),32);
    bufp->fullIData(oldp+314,(vlSelfRef.top__DOT__regfile__DOT__a2),32);
    bufp->fullIData(oldp+315,(vlSelfRef.top__DOT__regfile__DOT__a3),32);
    bufp->fullIData(oldp+316,(vlSelfRef.top__DOT__regfile__DOT__a4),32);
    bufp->fullIData(oldp+317,(vlSelfRef.top__DOT__regfile__DOT__a5),32);
    bufp->fullIData(oldp+318,(vlSelfRef.top__DOT__regfile__DOT__a6),32);
    bufp->fullIData(oldp+319,(vlSelfRef.top__DOT__regfile__DOT__a7),32);
    bufp->fullIData(oldp+320,(vlSelfRef.top__DOT__regfile__DOT__t0),32);
    bufp->fullIData(oldp+321,(vlSelfRef.top__DOT__regfile__DOT__t1),32);
    bufp->fullIData(oldp+322,(vlSelfRef.top__DOT__regfile__DOT__t2),32);
    bufp->fullIData(oldp+323,(vlSelfRef.top__DOT__regfile__DOT__t3),32);
    bufp->fullIData(oldp+324,(vlSelfRef.top__DOT__regfile__DOT__t4),32);
    bufp->fullIData(oldp+325,(vlSelfRef.top__DOT__regfile__DOT__t5),32);
    bufp->fullIData(oldp+326,(vlSelfRef.top__DOT__regfile__DOT__t6),32);
    bufp->fullIData(oldp+327,(vlSelfRef.top__DOT__regfile__DOT__s0),32);
    bufp->fullIData(oldp+328,(vlSelfRef.top__DOT__regfile__DOT__s1),32);
    bufp->fullIData(oldp+329,(vlSelfRef.top__DOT__regfile__DOT__s2),32);
    bufp->fullIData(oldp+330,(vlSelfRef.top__DOT__regfile__DOT__s3),32);
    bufp->fullIData(oldp+331,(vlSelfRef.top__DOT__regfile__DOT__s4),32);
    bufp->fullIData(oldp+332,(vlSelfRef.top__DOT__regfile__DOT__s5),32);
    bufp->fullIData(oldp+333,(vlSelfRef.top__DOT__regfile__DOT__s6),32);
    bufp->fullIData(oldp+334,(vlSelfRef.top__DOT__regfile__DOT__s7),32);
    bufp->fullIData(oldp+335,(vlSelfRef.top__DOT__regfile__DOT__s8),32);
    bufp->fullIData(oldp+336,(vlSelfRef.top__DOT__regfile__DOT__s9),32);
    bufp->fullIData(oldp+337,(vlSelfRef.top__DOT__regfile__DOT__s10),32);
    bufp->fullIData(oldp+338,(vlSelfRef.top__DOT__regfile__DOT__s11),32);
    bufp->fullIData(oldp+339,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[0]),32);
    bufp->fullIData(oldp+340,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[1]),32);
    bufp->fullIData(oldp+341,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[2]),32);
    bufp->fullIData(oldp+342,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[3]),32);
    bufp->fullIData(oldp+343,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[4]),32);
    bufp->fullIData(oldp+344,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[5]),32);
    bufp->fullIData(oldp+345,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[6]),32);
    bufp->fullIData(oldp+346,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[7]),32);
    bufp->fullIData(oldp+347,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[8]),32);
    bufp->fullIData(oldp+348,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[9]),32);
    bufp->fullIData(oldp+349,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[10]),32);
    bufp->fullIData(oldp+350,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[11]),32);
    bufp->fullIData(oldp+351,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[12]),32);
    bufp->fullIData(oldp+352,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[13]),32);
    bufp->fullIData(oldp+353,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[14]),32);
    bufp->fullIData(oldp+354,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[15]),32);
    bufp->fullIData(oldp+355,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[16]),32);
    bufp->fullIData(oldp+356,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[17]),32);
    bufp->fullIData(oldp+357,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[18]),32);
    bufp->fullIData(oldp+358,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[19]),32);
    bufp->fullIData(oldp+359,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[20]),32);
    bufp->fullIData(oldp+360,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[21]),32);
    bufp->fullIData(oldp+361,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[22]),32);
    bufp->fullIData(oldp+362,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[23]),32);
    bufp->fullIData(oldp+363,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[24]),32);
    bufp->fullIData(oldp+364,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[25]),32);
    bufp->fullIData(oldp+365,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[26]),32);
    bufp->fullIData(oldp+366,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[27]),32);
    bufp->fullIData(oldp+367,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[28]),32);
    bufp->fullIData(oldp+368,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[29]),32);
    bufp->fullIData(oldp+369,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[30]),32);
    bufp->fullIData(oldp+370,(vlSelfRef.top__DOT__regfile__DOT__registerfile_array[31]),32);
    bufp->fullCData(oldp+371,(vlSelfRef.top__DOT__regfile_mux__DOT__sel),2);
    bufp->fullIData(oldp+372,(vlSelfRef.top__DOT__regfile_mux__DOT__in0),32);
    bufp->fullIData(oldp+373,(vlSelfRef.top__DOT__regfile_mux__DOT__in1),32);
    bufp->fullIData(oldp+374,(vlSelfRef.top__DOT__regfile_mux__DOT__in2),32);
    bufp->fullIData(oldp+375,(vlSelfRef.top__DOT__regfile_mux__DOT__out),32);
    bufp->fullCData(oldp+376,(vlSelfRef.top__DOT__sign_extend__DOT__ImmSrc),3);
    bufp->fullIData(oldp+377,(vlSelfRef.top__DOT__sign_extend__DOT__ImmInput),32);
    bufp->fullIData(oldp+378,(vlSelfRef.top__DOT__sign_extend__DOT__ImmExt),32);
}
